aliases:
    asap$: npmassets/asap/asap
    backbone$: npmassets/backbone/backbone
    bootstrap$: oroviewswitcher/js/bootstrap
    bootstrap-alert$: npmassets/bootstrap/js/dist/alert
    chaplin$: oroui/lib/chaplin
    cryptojs/sha256$: npmassets/crypto-js/sha256
    jquery$: npmassets/jquery/dist/jquery
    module-config$: oroui/js/app/services/module-config
    oroui/js/app$: oroviewswitcher/js/app/views/demo/demo
    routing$: fosjsrouting/js/router
    slick$: npmassets/slick-carousel/slick/slick
    underscore$: npmassets/underscore/underscore
app-modules: []
configs:
    orotranslation/js/translator: {}
    oroui/js/component-shortcuts-manager: {}
    oroviewswitcher/js/app/views/demo/demo: {}
    oroviewswitcher/js/app/views/device-switcher-view: {}
dynamic-imports:
    oroviewswitcher:
        - orotranslation/js/translator
        - oroui/js/messenger
map:
    "*":
        backbone: oroui/js/extend/backbone
        chaplin: oroui/js/extend/chaplin
        jquery: oroui/js/extend/jquery
        underscore: oroui/js/extend/underscore
    chaplin:
        backbone: backbone
    oroui/js/app/components/base/component:
        backbone: backbone
        chaplin: chaplin
    oroui/js/extend/backbone:
        backbone: backbone
    oroui/js/extend/chaplin:
        chaplin: chaplin
    oroui/js/extend/jquery:
        jquery: jquery
    oroui/js/extend/underscore:
        underscore: underscore
    oroui/js/mediator:
        chaplin: chaplin
    oroui/js/tools:
        chaplin: chaplin
