services:
    oro_filter.extension.orm_filter:
        class: Oro\Bundle\FilterBundle\Grid\Extension\OrmFilterExtension
        arguments:
            - '@oro_datagrid.configuration.provider.raw'
            - '@oro_filter.extension.orm_filter_bag'
            - '@oro_filter.provider.state.filters'
            - '@translator'
        tags:
            - { name: oro_datagrid.extension }

    oro_filter.extension.orm_filter_bag:
        class: Oro\Bundle\FilterBundle\Filter\FilterBag
        public: true
        arguments:
            - [] # filter names
            - ~ # service locator

    oro_filter.datagrid.column_options_guesser:
        class: Oro\Bundle\FilterBundle\Grid\DefaultColumnFilteringOptionsGuesser
        tags:
            - { name: oro_datagrid.column_options_guesser }

    oro_filter.provider.datemodifierprovider:
        class: Oro\Bundle\FilterBundle\Provider\DateModifierProvider

    oro_filter.expression.date.parser:
        class: Oro\Bundle\FilterBundle\Expression\Date\Parser
        arguments:
            - '@oro_locale.settings'

    oro_filter.expression.date.lexer:
        class: Oro\Bundle\FilterBundle\Expression\Date\Lexer
        arguments:
            - '@translator'
            - '@oro_filter.provider.datemodifierprovider'

    oro_filter.expression.date.compiler:
        class: Oro\Bundle\FilterBundle\Expression\Date\Compiler
        arguments:
            - '@oro_filter.expression.date.lexer'
            - '@oro_filter.expression.date.parser'

    oro_filter.builder.many_relation:
        class: Oro\Bundle\FilterBundle\Datasource\ManyRelationBuilder
        calls:
            - [addBuilder, ['@oro_filter.builder.many_relation.orm']]

    oro_filter.builder.many_relation.orm:
        class: Oro\Bundle\FilterBundle\Datasource\Orm\OrmManyRelationBuilder
        arguments:
            - '@doctrine'

    oro_filter.utils.date_filter_modifier:
        class: Oro\Bundle\FilterBundle\Utils\DateFilterModifier
        arguments:
            - '@oro_filter.expression.date.compiler'

    oro_filter.provider.state.filters:
        class: Oro\Bundle\FilterBundle\Provider\State\FiltersStateProvider
        parent: oro_datagrid.provider.state.abtract
        lazy: true
        arguments:
            - '@oro_datagrid.tools.parameters_helper'

    oro_datagrid.provider.selected_fields.filters:
        class: Oro\Bundle\FilterBundle\Provider\SelectedFields\SelectedFieldsFromFiltersProvider
        public: false
        arguments:
            - '@oro_filter.provider.state.filters'
        tags:
            - { name: oro_datagrid.selected_fields_provider }
