##
# Services in this file are used for testing
#
# @see TagBundle/Tests/Functional/Controller/ImportExportControllerTest.php
##
services:
    oro_user.importexport.strategy.user.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace
        public: true

    oro_user.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        public: true
        calls:
            - [setDataConverter, ['@oro_user.importexport.template_fixture.data_converter']]
            - [setStrategy, ['@oro_user.importexport.strategy.user.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: 'Oro\Bundle\UserBundle\Entity\User', alias: oro_user.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: 'Oro\Bundle\UserBundle\Entity\User', alias: oro_user.add_or_replace }
