services:
    oro_entity_merge.form.type.merge:
        class: Oro\Bundle\EntityMergeBundle\Form\Type\MergeType
        tags:
            - { name: form.type, alias: "oro_entity_merge" }

    oro_entity_merge.form.type.merge_field:
        class: Oro\Bundle\EntityMergeBundle\Form\Type\MergeFieldType
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: "oro_entity_merge_field" }
