api:
    entities:
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/business_unit.md'
            actions:
                delete:
                    exclude: false # set manually because this entity is marked as a dictionary
                delete_list:
                    exclude: false # set manually because this entity is marked as a dictionary
                create:
                    exclude: false # set manually because this entity is marked as a dictionary
                update:
                    exclude: false # set manually because this entity is marked as a dictionary

        Oro\Bundle\OrganizationBundle\Entity\Organization:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/organization.md'
            actions:
                delete: false
                delete_list: false
                create: false
