services:
    oro_search.search.engine:
        class: Oro\Bundle\SearchBundle\Engine\Orm
        arguments:
            - '@doctrine'
            - '@oro_search.mapper'
            - '@event_dispatcher'
        calls:
            - [setLogQueries, ['%oro_search.log_queries%']]

    oro_search.search.engine.indexer:
        class: Oro\Bundle\SearchBundle\Engine\OrmIndexer
        arguments:
            - '@doctrine'
            - '@oro_entity.doctrine_helper'
            - '@oro_search.text_filtered_mapper'
            - '@oro_entity.entity_name_resolver'
