datagrids:
    attachment-grid:
        extended_entity_name: 'Oro\Bundle\AttachmentBundle\Entity\Attachment'
        source:
            type: orm
            query:
                select:
                    - attachment as att
                    - attachment.id as id
                    - attachment.comment as comment
                    - file.originalFilename as originalFilename
                    - file.fileSize as fileSize
                    - file.createdAt as createdAt
                from:
                    - { table: 'OroAttachmentBundle:Attachment', alias: attachment }
                join:
                    left:
                        - { join: attachment.file, alias: file }
                where:
                    and:
                      - entity.id = :entityId # entity with alias 'entity' sets in event listener
        columns:
            originalFilename:
                type: twig
                label: oro.attachment.file.filename.label
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/attachmentLink.html.twig
            fileSize:
                label: oro.attachment.file.file_size.label
                type: twig
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/fileSize.html.twig
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            comment:
                label: oro.attachment.comment.label
        properties:
            id: ~
            update_link:
                type:       url
                route:      oro_attachment_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_attachment
                params:     [ id ]
        actions:
            update:
                type:          dialog
                acl_resource:  oro_attachment_update
                label:         oro.grid.action.update
                icon:          pencil-square-o
                link:          update_link
                widgetOptions:
                    reload-grid-name: attachment-grid
                    options:
                        dialogOptions:
                            title: Update attachment
                            width: 550
                            allowMaximize: false
                            allowMinimize: false
                            modal: true
                            maximizedHeightDecreaseBy: minimize-bar
                messages:
                    saved: oro.attachment.action.saved
            delete:
                type:          delete
                acl_resource:  oro_attachment_delete
                label:         oro.grid.action.delete
                icon:          trash-o
                link:          delete_link

    base-attachment-files-grid:
        source:
            type: orm
            query:
                select:
                    - file_item as root
                    - file_item.sortOrder
                    - file.originalFilename as originalFilename
                    - CONCAT_WS(' ', fileOwner.firstName, fileOwner.lastName) as uploadedBy
                    - file.createdAt
                from:
                    - { table: 'OroAttachmentBundle:FileItem', alias: file_item }
                join:
                    left:
                        - { join: file_item.file, alias: file }
                        - { join: file.owner, alias: fileOwner }
                        - { join: file.digitalAsset, alias: digitalAsset }
                        - { join: digitalAsset.owner, alias: sourceOwner }
                where:
                    and:
                      - entity.id = :entityId # entity with alias 'entity' sets in event listener
        columns:
            sortOrder:
                label: oro.attachment.fileitem.sort_order.label
        properties:
            id: ~
        sorters:
            columns:
                sortOrder:
                    data_name: file_item.sortOrder
                createdAt:
                    data_name: file.createdAt
            default:
                sortOrder: ASC
        filters:
            columns:
                originalFilename:
                    type: string
                    data_name: originalFilename
                uploadedBy:
                    type: string
                    data_name: uploadedBy
                createdAt:
                    type:      datetime
                    data_name: language.createdAt

    attachment-files-grid:
        extends: base-attachment-files-grid
        options:
            entityHint: oro.attachment.fileitem.file.plural_label
        columns:
            originalFilename:
                label: oro.attachment.file.filename.label
                type: twig
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/fileLink.html.twig
            uploadedBy:
                label: oro.attachment.file.uploaded_by.label
                frontend_type: relation
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime

    attachment-images-grid:
        extends: base-attachment-files-grid
        options:
            entityHint: oro.attachment.fileitem.image.plural_label
        columns:
            image:
                label: oro.attachment.file.image.label
                type: twig
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/image.html.twig
            originalFilename:
                label: oro.attachment.file.name.label
                type: twig
                frontend_type: html
                template: OroAttachmentBundle:Attachment:Datagrid/Property/fileLink.html.twig
            uploadedBy:
                label: oro.attachment.file.uploaded_by.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
