entity_config:
    attachment:
        entity:
            form:
                block_config:
                    attachments:
                        title:              oro.attachment.block_titles.attachments.label
                        priority:           0

            items:
                # indicates whether attachments can be added to the entity or not
                enabled: # boolean
                    options:
                        priority:           100
                        default_value:      false
                        require_schema_update: true
                    form:
                        type:               Oro\Bundle\EntityExtendBundle\Form\Type\AssociationChoiceType
                        options:
                            block:          attachments
                            required:       true
                            label:          oro.attachment.enabled
                            association_class: 'OroAttachmentBundle:Attachment'

                # the max size in megabytes of attached file
                maxsize: # integer
                    options:
                        priority:           90
                        default_value:      1
                    constraints:
                        - NotBlank:         ~
                        - Type:             integer
                        - Range:
                            min:            1
                            max:            2047 # in bytes equivalents to ~2147483647 which max allowed value for fileSize column of File entity
                    form:
                        type:               Oro\Bundle\EntityExtendBundle\Form\Type\IntegerAssociationPropertyType
                        options:
                            block:          attachments
                            required:       false
                            label:          oro.attachment.maxsize
                            association_class: 'OroAttachmentBundle:Attachment'

                # the list of all allowed MIME types for attachments
                mimetypes: # string (MIME types are delimited by linefeed (\n) symbol)
                    options:
                        priority:           80
                    constraints:
                        - Oro\Bundle\AttachmentBundle\Validator\Constraints\MimeType: ~
                    form:
                        type:               Oro\Bundle\AttachmentBundle\Form\Type\FileMimeTypeConfigType
                        options:
                            block:          attachments
                            required:       false
                            label:          oro.attachment.mimetypes
                            tooltip:        oro.attachment.mimetypes.tooltip

                # this attribute can be used to prohibit changing the attachment association state (no matter whether
                # it is enabled or not) for the entity
                # if TRUE than the current state cannot be changed
                immutable: # boolean
                    options:
                        auditable:          false

        field:
            items:
                attachment:
                    options:
                        allowed_type:       [file, image]
                        auditable:          false
                    form:
                        type:               Oro\Bundle\AttachmentBundle\Form\Type\FileConfigType
                        options:
                            block:          general
                            subblock:       properties

                # the max size in megabytes of uploaded file
                maxsize: # integer
                    options:
                        value_type:         integer
                        allowed_type:       [file, image, multiFile, multiImage]
                    constraints:
                        - NotBlank:         ~
                        - Type:             integer
                        - Range:
                            min:            1
                            max:            2047 # in bytes equivalents to ~2147483647 which max allowed value for fileSize column of File entity
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            required:       true
                            label:          oro.attachment.config.file_size.label
                            block:          general
                            subblock:       properties
                            empty_data:     1
                            tooltip:        oro.attachment.max_size.tooltip

                # picture thumbnail width in pixels
                width: # integer
                    options:
                        value_type:         integer
                        allowed_type:       [image, multiImage]
                    constraints:
                        - NotBlank:         ~
                        - Type:             integer
                        - Range:
                              min:          1
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            required:       true
                            label:          oro.attachment.config.thumb_width.label
                            block:          general
                            subblock:       properties
                            empty_data:     32
                            tooltip:        oro.attachment.thumb_width.tooltip

                # picture thumbnail height in pixels
                height: # integer
                    options:
                        value_type:         integer
                        allowed_type:       [image, multiImage]
                    constraints:
                        - NotBlank:         ~
                        - Type:             integer
                        - Range:
                              min:          1
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            required:       true
                            label:          oro.attachment.config.thumb_height.label
                            block:          general
                            subblock:       properties
                            empty_data:     32
                            tooltip:        oro.attachment.thumb_height.tooltip

                # the list of all allowed MIME types
                mimetypes: # string (MIME types are delimited by linefeed (\n) symbol)
                    options:
                        allowed_type:       [file, image, multiFile, multiImage]
                    constraints:
                        - Oro\Bundle\AttachmentBundle\Validator\Constraints\MimeType: ~
                    form:
                        type:               Oro\Bundle\AttachmentBundle\Form\Type\FileMimeTypeConfigType
                        options:
                            block:          general
                            subblock:       properties
                            required:       false
                            label:          oro.attachment.mimetypes
                            tooltip:        oro.attachment.mimetypes.tooltip

                # the max number of files
                max_number_of_files: # integer
                    options:
                        value_type:         integer
                        allowed_type:       [multiFile, multiImage]
                    constraints:
                        - Type:             integer
                        - Range:
                              min:          1
                              max:          32767
                    form:
                        type:               Symfony\Component\Form\Extension\Core\Type\IntegerType
                        options:
                            required:       false
                            label:          oro.attachment.config.max_number_of_files.label
                            block:          general
                            subblock:       properties
                            tooltip:        oro.attachment.config.max_number_of_files.tooltip
