aliases:
    oroworkflow/transition-dialog-widget$: oroworkflow/js/app/widget/transition-dialog-widget
dynamic-imports:
    oroworkflow:
        - oroworkflow/js/app/components/button-component
        - oroworkflow/transition-dialog-widget
