services:
    oro_form.autocomplete.security:
        class: Oro\Bundle\FormBundle\Autocomplete\Security
        public: true
        arguments:
            - [] # autocomplete ACL resources
            - '@security.authorization_checker'

    oro_form.autocomplete.search_registry:
        class: Oro\Bundle\FormBundle\Autocomplete\SearchRegistry
        public: true
        arguments:
            - ~ # service locator for autocomplete search handlers

    oro_form.autocomplete.search_handler:
        class: Oro\Bundle\FormBundle\Autocomplete\SearchHandler
        abstract: true
        calls:
            - [initSearchIndexer, ["@oro_search.index", '@oro_search.provider.search_mapping']]
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
            - [setAclHelper,["@oro_security.acl_helper"]]
            - [setLogger,["@logger"]]

    oro_form.autocomplete.full_name.search_handler:
        class: Oro\Bundle\FormBundle\Autocomplete\FullNameSearchHandler
        abstract: true
        parent: oro_form.autocomplete.search_handler
        calls:
            - [ setEntityNameResolver, ['@oro_entity.entity_name_resolver'] ]
