services:
    # Form types
    oro_form.type.date:
        class: Oro\Bundle\FormBundle\Form\Type\OroDateType
        tags:
            - { name: form.type, alias: oro_date }

    oro_form.type.datetime:
        class: Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
        tags:
            - { name: form.type, alias: oro_datetime }

    oro_form.type.time_interval:
        class: Oro\Bundle\FormBundle\Form\Type\OroTimeIntervalType
        tags:
            - { name: form.type, alias: oro_time_interval }

    oro_form.type.duration:
        class: Oro\Bundle\FormBundle\Form\Type\OroDurationType
        tags:
            - { name: form.type, alias: oro_duration }

    oro_form.type.money:
        class: Oro\Bundle\FormBundle\Form\Type\OroMoneyType
        arguments:
            - '@oro_locale.settings'
            - '@oro_locale.formatter.number'
        tags:
            - { name: form.type, alias: oro_money }

    oro_form.type.choice:
        class: Oro\Bundle\FormBundle\Form\Type\OroChoiceType
        tags:
            - { name: form.type, alias: oro_choice }

    oro_form.type.percent:
        class: Oro\Bundle\FormBundle\Form\Type\OroPercentType
        tags:
            - { name: form.type, alias: oro_percent }

    oro_form.type.icon:
        class: Oro\Bundle\FormBundle\Form\Type\OroIconType
        arguments:
            - '@kernel'
        tags:
            - { name: form.type, alias: oro_icon_select }

    oro_form.type.entity_identifier:
        class: Oro\Bundle\FormBundle\Form\Type\EntityIdentifierType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: oro_entity_identifier }

    oro_form.type.entity_tree_select:
        class: Oro\Bundle\FormBundle\Form\Type\EntityTreeSelectType
        tags:
            - { name: form.type, alias: oro_entity_tree_select }

    oro_form.type.jqueryselect2_hidden:
        class: Oro\Bundle\FormBundle\Form\Type\OroJquerySelect2HiddenType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_form.autocomplete.search_registry'
            - '@oro_entity_config.provider.form'
        tags:
            - { name: form.type, alias: oro_jqueryselect2_hidden }

    oro_form.type.multiple_entity:
        class: Oro\Bundle\FormBundle\Form\Type\MultipleEntityType
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@security.authorization_checker'
        tags:
            - { name: form.type, alias: oro_multiple_entity }

    oro_form.type.collection:
        class: Oro\Bundle\FormBundle\Form\Type\CollectionType
        tags:
             - { name: form.type, alias: oro_collection }

    oro_form.type.entity_create_or_select:
        class: Oro\Bundle\FormBundle\Form\Type\OroEntityCreateOrSelectType
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: form.type, alias: oro_entity_create_or_select }

    oro_form.type.entity_create_or_select_choice:
        class: Oro\Bundle\FormBundle\Form\Type\OroEntityCreateOrSelectChoiceType
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: form.type, alias: oro_entity_create_or_select_choice }

    oro_form.type.simple_color_picker:
        class: Oro\Bundle\FormBundle\Form\Type\OroSimpleColorPickerType
        arguments:
            - '@oro_config.user'
            - '@translator'
        tags:
            - { name: form.type, alias: oro_simple_color_picker }

    oro_form.type.simple_color_choice:
        class: Oro\Bundle\FormBundle\Form\Type\OroSimpleColorChoiceType
        arguments:
            - '@oro_config.user'
        tags:
            - { name: form.type, alias: oro_simple_color_choice }

    oro_form.type.color_table:
        class: Oro\Bundle\FormBundle\Form\Type\OroColorTableType
        tags:
            - { name: form.type, alias: oro_color_table }

    oro_form.type.rich_text:
        class: Oro\Bundle\FormBundle\Form\Type\OroRichTextType
        arguments:
            - '@oro_config.user'
            - '@oro_form.provider.html_tag_provider'
            - '@assets.context'
            - '@oro_ui.html_tag_helper'
        calls:
            - [setAssetHelper, ['@assets.packages']]
        tags:
            - { name: form.type, alias: oro_rich_text }

    oro_form.type.resizeable_rich_text:
        class: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
        tags:
            - { name: form.type, alias: oro_resizeable_rich_text }

    oro_form.type.data_changeset:
        class: Oro\Bundle\FormBundle\Form\Type\DataChangesetType
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: form.type, alias: oro_data_changeset }

    oro_form.type.entity_changeset:
        class: Oro\Bundle\FormBundle\Form\Type\EntityChangesetType
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: form.type, alias: oro_entity_changeset }

    oro_form.type.select2:
        class: Oro\Bundle\FormBundle\Form\Type\Select2Type
        abstract: true

    oro_form.type.select2_hidden:
        class: Oro\Bundle\FormBundle\Form\Type\Select2HiddenType
        tags:
            - { name: form.type, alias: oro_select2_hidden }

    oro_form.type.oro_select2_choice:
        class: Oro\Bundle\FormBundle\Form\Type\Select2ChoiceType
        tags:
            - { name: form.type, alias: oro_select2_choice }

    oro_form.type.oro_select2_entity:
        class: Oro\Bundle\FormBundle\Form\Type\Select2EntityType
        tags:
            - { name: form.type, alias: oro_select2_entity }

    # Form extensions
    oro_form.extension.data_block:
        class: Oro\Bundle\FormBundle\Form\Extension\DataBlockExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.date_time_extension:
         class: Oro\Bundle\FormBundle\Form\Extension\DateTimeExtension
         tags:
             - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }

    oro_form.extension.client_validation:
        class: Oro\Bundle\FormBundle\Form\Extension\ClientValidationExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.tooltip_extension:
        class: Oro\Bundle\FormBundle\Form\Extension\TooltipFormExtension
        arguments:
            - '@oro_entity_config.provider.entity'
            - '@translator.default'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.hint_extension:
        class: Oro\Bundle\FormBundle\Form\Extension\HintFormExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.constraint_as_option:
        class: Oro\Bundle\FormBundle\Form\Extension\ConstraintAsOptionExtension
        arguments:
            - '@oro_form.validator.constraint_factory'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.js_validation:
        class: Oro\Bundle\FormBundle\Form\Extension\JsValidationExtension
        arguments:
            - '@oro_form.extension.js_validation.constraints_provider'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.js_validation.constraints_provider:
        class: Oro\Bundle\FormBundle\Form\Extension\JsValidation\ConstraintsProvider
        arguments:
            - '@validator.mapping.class_metadata_factory'


    oro_form.extension.js_validation.repeated:
        class: Oro\Bundle\FormBundle\Form\Extension\JsValidation\RepeatedTypeExtension
        tags:
            - { name: form.type_extension, alias: repeated, extended_type: Symfony\Component\Form\Extension\Core\Type\RepeatedType }

    oro_form.extension.additional_attr:
        class: Oro\Bundle\FormBundle\Form\Extension\AdditionalAttrExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.data_transformer:
        class: Oro\Bundle\FormBundle\Form\Extension\DataTransformerExtension
        arguments:
            - '@service_container'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.sortable:
        class: Oro\Bundle\FormBundle\Form\Extension\SortableExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.extra_fields_validation:
        class: Oro\Bundle\FormBundle\Form\Extension\ExtraFieldsValidationExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    oro_form.extension.strip_tags:
        class: Oro\Bundle\FormBundle\Form\Extension\StripTagsExtension
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
            - { name: container.service_subscriber, id: oro_ui.html_tag_helper }

    oro_form.type.encoded_placeholder_password:
        class: Oro\Bundle\FormBundle\Form\Type\OroEncodedPlaceholderPasswordType
        arguments:
            - '@oro_security.encoder.default'
        tags:
            - { name: form.type, alias: oro_encoded_placeholder_password }

    oro_form.type.textlist:
        class: Oro\Bundle\FormBundle\Form\Type\OroTextListType
        tags:
            - { name: form.type, alias: oro_textlist }

    oro_form.type.oro_entity_create_or_select_inline:
        class: Oro\Bundle\FormBundle\Form\Type\OroEntitySelectOrCreateInlineType
        arguments:
            - '@security.authorization_checker'
            - '@oro_entity_config.config_manager'
            - '@doctrine.orm.entity_manager'
            - '@oro_form.autocomplete.search_registry'
        tags:
            - { name: form.type, alias: oro_entity_create_or_select_inline }

    oro_form.type.oro_autocomplete:
        class: Oro\Bundle\FormBundle\Form\Type\OroAutocompleteType
        arguments:
            - '@oro_form.autocomplete.search_registry'
        tags:
            - { name: form.type, alias: oro_autocomplete }

    oro_form.type.link:
        class: Oro\Bundle\FormBundle\Form\Type\LinkType
        tags:
            - { name: form.type, alias: oro_link_type }

    oro_form.type.download_links:
        class: Oro\Bundle\FormBundle\Form\Type\DownloadLinksType
        arguments:
            - '@assets.packages'
        tags:
            - { name: form.type, alias: oro_download_links_type }

    oro_form.form_handler.api:
        class: Oro\Bundle\FormBundle\Form\Handler\ApiFormHandler
        arguments:
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    oro_form.validator.entity_class:
        class: Oro\Bundle\FormBundle\Validator\Constraints\EntityClassValidator
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity.entity_class_name_helper'
        tags:
            - { name: validator.constraint_validator, alias: oro_form.entity_class_validator }

    oro_form.validator.related_entity:
        class: Oro\Bundle\FormBundle\Validator\Constraints\RelatedEntityValidator
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity.entity_class_name_helper'
        tags:
            - { name: validator.constraint_validator, alias: oro_form.related_entity_validator }

    oro_form.validator.unchangable_field:
        class: Oro\Bundle\FormBundle\Validator\Constraints\UnchangeableFieldValidator
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: validator.constraint_validator, alias: oro_form.unchangable_field_validator }

    oro_form.related_entity.form.transformer.api:
        class: Oro\Bundle\FormBundle\Form\DataTransformer\RelatedEntityTransformer
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity.entity_class_name_helper'
            - '@security.authorization_checker'

    oro_form.related_entity.form.type.api:
        class: Oro\Bundle\FormBundle\Form\Type\RelatedEntityApiType
        arguments:
            - '@oro_form.related_entity.form.transformer.api'
        tags:
            - { name: form.type, alias: oro_related_entity_api }

    oro_form.related_entity_collection.form.type.api:
        class: Oro\Bundle\FormBundle\Form\Type\RelatedEntityCollectionApiType
        tags:
            - { name: form.type, alias: oro_related_entity_collection_api }

    oro_form.related_entity_standalone_collection.form.type.api:
        class: Oro\Bundle\FormBundle\Form\Type\RelatedEntityStandaloneCollectionApiType
        tags:
            - { name: form.type, alias: oro_related_entity_standalone_collection_api }

    oro_form.type.hidden_number:
        class: Oro\Bundle\FormBundle\Form\Type\OroHiddenNumberType
        arguments:
            - '@oro_locale.formatter.number'
        tags:
            - { name: form.type, alias: oro_hidden_number }

    oro_form.type.checkbox:
        class: Oro\Bundle\FormBundle\Form\Type\CheckboxType
        tags:
            - { name: form.type, alias: oro_checkbox }
