services:
    oro_form.importexport.primary_item_collection_normalizer:
        class: Oro\Bundle\FormBundle\ImportExport\Serializer\Normalizer\PrimaryItemCollectionNormalizer
        tags:
            - { name: oro_importexport.normalizer, priority: -5 }
