services:
    _defaults:
        public: true

    Oro\Bundle\ViewSwitcherBundle\Controller\Frontend\AjaxApplicationUrlController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
