aliases:
    routing$: fosjsrouting/js/router
app-modules:
    - oronavigation/js/app/modules/navigation-module
configs:
    oronavigation/js/routes-loader: {}
dynamic-imports:
    oronavigation:
        - routing
