parameters:
    hwi_oauth.authentication.provider.oauth.class: Oro\Bundle\SSOBundle\Security\OAuthProvider
    hwi_oauth.resource_owner.google.class: Oro\Bundle\SSOBundle\OAuth\ResourceOwner\GoogleResourceOwner

services:
    oro_sso.oauth_provider:
        class: Oro\Bundle\SSOBundle\Security\Core\User\OAuthUserProvider
        public: true
        arguments: ['@oro_user.manager', '@oro_config.global']

    oro_sso.event_listener.user_email_change_listener:
        class: Oro\Bundle\SSOBundle\EventListener\UserEmailChangeListener
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\UserBundle\Entity\User', event: preUpdate }

    oro_sso.token.factory.oauth:
        class: Oro\Bundle\SSOBundle\Security\OAuthTokenFactory
