services:
    oro_api.update.processor:
        class: Oro\Bundle\ApiBundle\Processor\UpdateProcessor
        public: false
        arguments:
            - '@oro_api.processor_bag'
            - update
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.update.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\Update\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: update, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    oro_api.update.json_api.validate_request_data:
        class: Oro\Bundle\ApiBundle\Processor\Update\JsonApi\ValidateRequestData
        arguments:
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_input, requestType: json_api, priority: 90 }

    oro_api.update.normalize_entity_id:
        class: Oro\Bundle\ApiBundle\Processor\Update\NormalizeEntityId
        arguments:
            - '@oro_api.entity_id_transformer_registry'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_input, priority: -110 }

    #
    # security_check
    #

    oro_api.update.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - EDIT
        calls:
            - [setDoctrineHelper, ['@oro_api.doctrine_helper']]
            - [setAclGroupProvider, ['@oro_security.acl.group_provider.chain']]
        tags:
            - { name: oro.api.processor, action: update, group: security_check, priority: 10 }

    #
    # load_data
    #

    #
    # data_security_check
    #

    oro_api.update.entity_object_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityObjectSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
            - EDIT
        tags:
            - { name: oro.api.processor, action: update, group: data_security_check, priority: 10 }

    #
    # transform_data
    #

    #
    # save_data
    #

    oro_api.update.save_entity:
        class: Oro\Bundle\ApiBundle\Processor\Update\SaveEntity
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: update, group: save_data, priority: -10 }

    #
    # normalize_data
    #

    oro_api.update.load_normalized_entity:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadNormalizedEntity
        arguments:
            - '@oro_api.action_processor_bag'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_data, priority: -10 }

    #
    # finalize
    #

    #
    # normalize_result
    #
