services:
    oro_api.get_list.processor:
        class: Oro\Bundle\ApiBundle\Processor\GetListProcessor
        arguments:
            - '@oro_api.processor_bag'
            - get_list
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.get_list.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\GetList\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    #
    # security_check
    #

    #
    # build_query
    #

    #
    # load_data
    #

    oro_api.get_list.load_data_by_sql_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntitiesBySqlQuery
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -20 }

    #
    # data_security_check
    #

    #
    # normalize_data
    #

    #
    # finalize
    #

    oro_api.get_list.assert_has_result:
        class: Oro\Bundle\ApiBundle\Processor\GetList\AssertHasResult
        tags:
            - { name: oro.api.processor, action: get_list, group: finalize, priority: -250 }

    #
    # normalize_result
    #
