aliases:
    oro/datagrid/action/map-action$: oroaddress/js/datagrid/action/map-action
app-modules:
    - oroaddress/js/app/modules/validator-constraints-module
configs:
    oroaddress/js/region/view: {}
dynamic-imports:
    oroaddress:
        - oroaddress/js/mapservice/googlemaps
        - oroaddress/js/region/view
        - oroaddress/js/validator/name-or-organization
