services:
    oro_organization.api.config.add_owner_validator:
        class: Oro\Bundle\OrganizationBundle\Api\Processor\Config\AddOwnerValidator
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_security.owner.ownership_metadata_provider'
            - '@oro_api.validation_helper'
        tags:
            - { name: oro.api.processor, action: get_config, extra: '!identifier_fields_only&!descriptions&definition', targetAction: update|create|update_relationship|add_relationship|delete_relationship|update_subresource|add_subresource|delete_subresource, priority: -50 }

    oro_organization.api.set_ownership_associations:
        class: Oro\Bundle\OrganizationBundle\Api\Processor\SetOwnershipAssociations
        arguments:
            - '@oro_api.form_property_accessor'
            - '@oro_security.token_accessor'
            - '@oro_security.owner.ownership_metadata_provider'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, parentAction: create, priority: 10 }
