dynamic-imports:
    oroimap:
        - oroimap/js/app/components/account-type-component
        - oroimap/js/app/components/check-config-settings
        - oroimap/js/app/components/check-connection-component
        - oroimap/js/app/components/google-sync-checkbox-component
        - oroimap/js/app/components/imap-gmail-component
