aliases:
    asap$: npmassets/asap/asap
    backbone$: npmassets/backbone/backbone
    base64$: oroui/js/extend/base64
    bootstrap$: oroui/blank/js/bootstrap
    bootstrap-alert$: npmassets/bootstrap/js/dist/alert
    bootstrap-dropdown$: npmassets/bootstrap/js/dist/dropdown
    bootstrap-modal$: npmassets/bootstrap/js/dist/modal
    bootstrap-popover$: npmassets/bootstrap/js/dist/popover
    bootstrap-scrollspy$: npmassets/bootstrap/js/dist/scrollspy
    bootstrap-tab$: npmassets/bootstrap/js/dist/tab
    bootstrap-tooltip$: npmassets/bootstrap/js/dist/tooltip
    bootstrap-typeahead$: oroui/lib/bootstrap/bootstrap-typeahead
    bootstrap-util$: npmassets/bootstrap/js/dist/util
    chaplin$: oroui/lib/chaplin
    controllers/page-controller$: oroui/js/app/controllers/page-controller
    cryptojs/core$: npmassets/crypto-js/core
    cryptojs/sha256$: npmassets/crypto-js/sha256
    css-vars-ponyfill$: npmassets/css-vars-ponyfill/dist/css-vars-ponyfill
    datepair$: npmassets/datepair.js/dist/datepair
    extend-popper$: oroui/js/extend/popper
    jquery$: npmassets/jquery/dist/jquery
    jquery-ui$: oroui/js/jquery-ui
    jquery.cookie$: npmassets/jquery.cookie/jquery.cookie
    jquery.form$: npmassets/jquery-form/src/jquery.form
    jquery.mousewheel$: npmassets/jquery-mousewheel/jquery.mousewheel
    jquery.multiselect$: npmassets/jquery-ui-multiselect-widget/src/jquery.multiselect.min
    jquery.multiselect.filter$: npmassets/jquery-ui-multiselect-widget/src/jquery.multiselect.filter.min
    jquery.numeric$: npmassets/jquery-numeric/jquery.numeric
    jquery.select2$: npmassets/@oroinc/select2/select2
    jquery.timepicker$: npmassets/timepicker/jquery.timepicker
    jquery.uniform$: npmassets/jquery.uniform/src/js/jquery.uniform
    module-config$: oroui/js/app/services/module-config
    oro/block-widget$: oroui/js/widget/block-widget
    oroui/js/widget-manager$: oroui/js/widget/widget-manager
    overlayScrollbars$: npmassets/overlayscrollbars/js/OverlayScrollbars
    popper$: npmassets/popper.js/dist/umd/popper
    scriptjs$: npmassets/scriptjs/dist/script
    styled-scroll-bar$: oroui/js/app/plugins/styled-scroll-bar
    underscore$: npmassets/underscore/underscore
app-modules:
    - oroui/js/app/modules/ajax-error-module
    - oroui/js/app/modules/component-shortcuts-module
    - oroui/js/app/modules/css-variable-module
    - oroui/js/app/modules/focus-visible
    - oroui/js/app/modules/init-layout
    - oroui/js/app/modules/input-widgets
    - oroui/js/app/modules/layout-module
    - oroui/js/app/modules/messenger-module
    - oroui/js/app/modules/styled-scroll-bar-module
    - oroui/js/app/modules/viewport-module
    - oroui/js/app/modules/widgets-module
    - oroui/js/extend/scriptjs
configs:
    controllers/page-controller: {}
    oroui/js/app: {}
    oroui/js/app/components/base/component-container-mixin: {}
    oroui/js/app/components/tabs-component: {}
    oroui/js/app/plugins/styled-scroll-bar: {}
    oroui/js/app/views/flash-message-view: {}
    oroui/js/app/views/page/messages-view: {}
    oroui/js/app/views/tab-collection-view: {}
    oroui/js/app/views/tab-item-view: {}
    oroui/js/component-shortcuts-manager: {}
    oroui/js/css-variables-manager: {}
    oroui/js/error: {}
    oroui/js/extend/bootstrap/bootstrap-dropdown: {}
    oroui/js/extend/scriptjs: {}
    oroui/js/modal: {}
    oroui/js/tools/highlighter/highlighter-favicon: {}
    oroui/js/tools/highlighter/highlighter-title: {}
    oroui/js/tools/scroll-helper: {}
    oroui/js/viewport-manager: {}
dynamic-imports:
    oroui:
        - controllers/page-controller
        - oro/block-widget
        - oroui/blank/js/extend/bootstrap
        - oroui/js/app/components/ajax-button
        - oroui/js/app/components/app-loading-bar-component
        - oroui/js/app/components/app-loading-mask-component
        - oroui/js/app/components/jquery-widget-component
        - oroui/js/app/components/tabs-component
        - oroui/js/app/components/view-component
        - oroui/js/app/components/viewport-component
        - oroui/js/app/components/widget-component
        - oroui/js/app/components/widget-form-component
        - oroui/js/app/views/datepicker/datepicker-view
        - oroui/js/app/views/datepicker/datetimepicker-view
        - oroui/js/app/views/element-value-copy-to-clipboard-view
        - oroui/js/app/views/input-widget/number
        - oroui/js/app/views/input-widget/select2
        - oroui/js/app/views/input-widget/uniform-file
        - oroui/js/app/views/input-widget/uniform-select
        - oroui/js/app/views/layout-subtree-view
        - oroui/js/app/views/page/content-view
        - oroui/js/app/views/page/messages-view
        - oroui/js/app/views/show-more/inline-show-more-view
        - oroui/js/app/views/show-more/table-show-more-view
        - oroui/js/app/views/swipeable-view
        - oroui/js/content-processor/pinned-dropdown-button
        - oroui/js/delete-confirmation
        - oroui/js/error
        - oroui/js/layout
        - oroui/js/mediator
        - oroui/js/messenger
        - oroui/js/modal
        - oroui/js/standart-confirmation
        - oroui/js/tools
        - oroui/js/tools/api-accessor
        - oroui/js/tools/manage-focus
        - oroui/js/widget/collapse-group-widget
        - oroui/js/widget/collapse-widget
map:
    "*":
        alert.js: bootstrap-alert
        backbone: oroui/js/extend/backbone
        bootstrap: oroui/blank/js/extend/bootstrap
        chaplin: oroui/js/extend/chaplin
        dropdown.js: bootstrap-dropdown
        jquery: oroui/js/extend/jquery
        jquery-ui: oroui/js/jquery-ui-datepicker-l10n
        jquery.multiselect: oroui/js/extend/jquery.multiselect
        jquery.multiselect.filter: oroui/js/extend/jquery.multiselect-filter
        jquery.select2: oroui/js/extend/select2
        jquery.timepicker: oroui/js/extend/jquery.timepicker
        jquery.uniform: oroui/js/extend/jquery.uniform
        modal.js: bootstrap-modal
        popover.js: bootstrap-popover
        popper: extend-popper
        popper.js: popper
        scriptjs: oroui/js/extend/scriptjs
        scrollspy.js: bootstrap-scrollspy
        tab.js: bootstrap-tab
        tooltip.js: bootstrap-tooltip
        underscore: oroui/js/extend/underscore
        util.js: bootstrap-util
    chaplin:
        backbone: backbone
    extend-popper:
        popper: popper
    oroui/blank/js/extend/bootstrap:
        bootstrap: bootstrap
    oroui/js/app/components/base/component:
        backbone: backbone
        chaplin: chaplin
    oroui/js/extend/backbone:
        backbone: backbone
    oroui/js/extend/chaplin:
        chaplin: chaplin
    oroui/js/extend/jquery:
        jquery: jquery
    oroui/js/extend/jquery-ui:
        jquery-ui: jquery-ui
    oroui/js/extend/jquery.multiselect:
        jquery.multiselect: jquery.multiselect
    oroui/js/extend/jquery.multiselect-filter:
        jquery.multiselect.filter: jquery.multiselect.filter
    oroui/js/extend/jquery.timepicker:
        jquery.timepicker: jquery.timepicker
    oroui/js/extend/jquery.uniform:
        jquery.uniform: jquery.uniform
    oroui/js/extend/scriptjs:
        scriptjs: scriptjs
    oroui/js/extend/select2:
        jquery.select2: jquery.select2
    oroui/js/extend/underscore:
        underscore: underscore
    oroui/js/jquery-timepicker-l10n:
        jquery.timepicker: jquery.timepicker
    oroui/js/jquery-ui-datepicker-l10n:
        jquery-ui: oroui/js/extend/jquery-ui
    oroui/js/mediator:
        chaplin: chaplin
    oroui/js/select2-l10n:
        jquery.select2: jquery.select2
    oroui/js/tools:
        chaplin: chaplin
shim:
    bootstrap-typeahead:
        imports:
            - jQuery=jquery
    datepair:
        exports: Datepair
    jquery:
        expose:
            - $
            - jQuery
    jquery.form:
        imports:
            - jQuery=jquery
    jquery.multiselect:
        imports:
            - jQuery=jquery
    jquery.multiselect.filter:
        imports:
            - jQuery=jquery
    jquery.select2:
        exports: Select2
        imports:
            - jQuery=jquery
    jquery.uniform:
        imports:
            - jQuery=jquery
    oroui/js/app/services/app-ready-load-modules:
        expose: loadModules
