placeholders:
    placeholders:
        js_modules_config:
            items:
                translation_js_modules_config:
                    order: 100

    items:
        translation_js_modules_config:
            template: OroTranslationBundle::js_modules_config.html.twig
