services:
    # Services for WorkflowData serialization
    oro_workflow.serializer.data.serializer:
        class: Oro\Bundle\WorkflowBundle\Serializer\WorkflowDataSerializer
        public: true
        arguments:
          - ['@oro_workflow.serializer.data.normalizer']
          - ['@serializer.encoder.json']
        calls:
          - [setWorkflowRegistry,  ['@oro_workflow.registry.system']]

    oro_workflow.serializer.data.serializer.link:
        public: false
        tags:
            - { name: oro_service_link, service: oro_workflow.serializer.data.serializer }

    oro_workflow.serializer.data.normalizer:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\WorkflowDataNormalizer
        arguments:
            - !tagged_iterator oro_workflow.attribute_normalizer

    oro_workflow.serializer.variable.normalizer:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\WorkflowVariableNormalizer
        parent: oro_workflow.serializer.data.normalizer
        arguments:
            - '@doctrine'

    oro_workflow.serializer.data.attribute_normalizer.standard:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\StandardAttributeNormalizer
        tags:
            - { name: oro_workflow.attribute_normalizer }

    oro_workflow.serializer.data.attribute_normalizer.entity:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\EntityAttributeNormalizer
        arguments:
            - '@doctrine'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_workflow.attribute_normalizer }

    oro_workflow.serializer.data.attribute_normalizer.multiple_entity:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\MultipleEntityAttributeNormalizer
        arguments:
            - '@doctrine'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_workflow.attribute_normalizer }

    oro_workflow.serializer.handler.workflow_result:
        class: Oro\Bundle\WorkflowBundle\Serializer\Handler\WorkflowResultHandler
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            -
              name: jms_serializer.handler
              method: workflowResultToJson
              type: Oro\Bundle\WorkflowBundle\Model\WorkflowResult
              format: json
              direction: serialization

    # Services for ProcessData serialization
    oro_workflow.serializer.process.serializer:
        class: Oro\Bundle\WorkflowBundle\Serializer\ProcessDataSerializer
        arguments:
          -
              - '@oro_workflow.serializer.process.normalizer.process_data'
              - '@oro_workflow.serializer.process.normalizer.entity'
              - '@oro_workflow.serializer.process.normalizer.object'
              - '@oro_workflow.serializer.process.normalizer.traversable'
              - '@oro_workflow.serializer.process.normalizer.scalar'

          - ['@serializer.encoder.json']

    oro_workflow.serializer.process.serializer.link:
        public: false
        tags:
            - { name: oro_service_link, service: oro_workflow.serializer.process.serializer }

    oro_workflow.serializer.process.normalizer.process_data:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\ProcessDataNormalizer
        arguments:
            - '@oro_entity.doctrine_helper'

    oro_workflow.serializer.process.normalizer.entity:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\ProcessEntityNormalizer
        arguments:
            - '@doctrine'
            - '@oro_entity.doctrine_helper'

    oro_workflow.serializer.process.normalizer.object:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\ProcessObjectNormalizer

    oro_workflow.serializer.process.normalizer.traversable:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\ProcessTraversableNormalizer

    oro_workflow.serializer.process.normalizer.scalar:
        class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\ProcessScalarNormalizer
