services:
    # Addresses form listeners
    oro_address.form.listener.address:
        class: Oro\Bundle\AddressBundle\Form\EventListener\AddressCountryAndRegionSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'

    oro_address.form.listener.address_identifier:
        class: 'Oro\Bundle\AddressBundle\Form\EventListener\AddressIdentifierSubscriber'
        public: false

    # Addresses form types
    oro_address.form.type.address:
        class: Oro\Bundle\AddressBundle\Form\Type\AddressType
        arguments:
            - '@oro_address.form.listener.address'
            - '@oro_address.form.listener.address_identifier'
        tags:
             - { name: form.type, alias: oro_address }

    oro_address.type.address_collection:
        class: Oro\Bundle\AddressBundle\Form\Type\AddressCollectionType
        tags:
             - { name: form.type, alias: oro_address_collection }

    oro_address.form.type.typed_address:
        class: Oro\Bundle\AddressBundle\Form\Type\TypedAddressType
        tags:
             - { name: form.type, alias: oro_typed_address }

    # Emails form types
    oro_address.form.type.email:
        class: Oro\Bundle\AddressBundle\Form\Type\EmailType
        tags:
             - { name: form.type, alias: oro_email }

    oro_address.type.email_collection:
        class: Oro\Bundle\AddressBundle\Form\Type\EmailCollectionType
        tags:
             - { name: form.type, alias: oro_email_collection }

    # Phones form types
    oro_address.form.type.phone:
        class: Oro\Bundle\AddressBundle\Form\Type\PhoneType
        tags:
             - { name: form.type, alias: oro_phone }

    oro_address.type.phone_collection:
        class: Oro\Bundle\AddressBundle\Form\Type\PhoneCollectionType
        tags:
             - { name: form.type, alias: oro_phone_collection }

    # Countries form types
    oro_address.form.type.country:
        class: Oro\Bundle\AddressBundle\Form\Type\CountryType
        tags:
            - { name: form.type, alias: oro_country }

    # Regions form types
    oro_address.form.type.region:
        class: Oro\Bundle\AddressBundle\Form\Type\RegionType
        tags:
            - { name: form.type, alias: oro_region }

    # Addresses forms
    oro_address.form.address:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "oro_address_form"
            - Oro\Bundle\AddressBundle\Form\Type\AddressType
            - ~

    # Addresses form handlers
    oro_address.form.handler.address:
        class: Oro\Bundle\AddressBundle\Form\Handler\AddressHandler
        arguments:
            - '@oro_address.form.address'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
