services:
    oro_address.provider.phone:
        class: Oro\Bundle\AddressBundle\Provider\PhoneProvider
        arguments:
            - [] # phone providers map
            - ~ # service locator for phone providers
            - '@oro_entity_config.provider.extend'

    oro_address.provider.country:
        class: Oro\Bundle\AddressBundle\Provider\CountryProvider
        public: true
        arguments:
            - '@oro_address.repository.country'

    oro_address.repository.country:
        class: Oro\Bundle\AddressBundle\Entity\Repository\CountryRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\AddressBundle\Entity\Country'

    oro_address.extension.action.type.map:
        class: Oro\Bundle\AddressBundle\Extension\Action\Actions\MapAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: map }

    oro_address.extension.js_valdation.constraints_provider_decorator:
        class: Oro\Bundle\AddressBundle\Extension\JsValidation\ConstraintsProviderDecorator
        decorates: oro_form.extension.js_validation.constraints_provider
        arguments:
            - '@oro_address.extension.js_valdation.constraints_provider_decorator.inner'

    oro_address.twig.extension.phone:
        class: Oro\Bundle\AddressBundle\Twig\PhoneExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_address.listener.translator_catalogue:
        class: Oro\Bundle\AddressBundle\EventListener\TranslatorCatalogueListener
        lazy: true
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oro_translation.after_catalogue_dump, method: onAfterCatalogueDump }
