aliases:
    orosidebar/widget/sticky-note$: orosidebar/sidebar_widgets/sticky_note/js/widget
dynamic-imports:
    orosidebar:
        - orosidebar/js/app/components/sidebar-component
        - orosidebar/widget/sticky-note
