parameters:
    oro_attachment.manager.attachment_manager.class:             Oro\Bundle\AttachmentBundle\Manager\AttachmentManager

    oro_attachment.entity.class:                                 Oro\Bundle\AttachmentBundle\Entity\Attachment
    oro_attachment.file.entity.class:                            Oro\Bundle\AttachmentBundle\Entity\File
    oro_attachment.manager.api.class:                            Oro\Bundle\AttachmentBundle\Entity\Manager\AttachmentApiEntityManager
    oro_attachment.manager.file.api.class:                       Oro\Bundle\AttachmentBundle\Entity\Manager\FileApiEntityManager

    oro_attachment.entity_config_dumper.extension.file.class:    Oro\Bundle\AttachmentBundle\Tools\FileEntityConfigDumperExtension
    oro_attachment.entity_config_dumper.extension.class:         Oro\Bundle\AttachmentBundle\Tools\AttachmentConfigDumperExtension
    oro_attachment.entity_generator.extension.class:             Oro\Bundle\AttachmentBundle\Tools\AttachmentEntityGeneratorExtension
    oro_attachment.migration.extension.attachment.class:         Oro\Bundle\AttachmentBundle\Migration\Extension\AttachmentExtension

    oro_attachment.serializer.file_normalizer.class:             Oro\Bundle\AttachmentBundle\ImportExport\FileNormalizer

    oro_attachment.placeholder.filter.class:                     Oro\Bundle\AttachmentBundle\Placeholder\PlaceholderFilter
    oro_attachment.attachment_grid_listener:                     Oro\Bundle\AttachmentBundle\EventListener\AttachmentGridListener

    oro_attachment.datagrid.action.dialog.class:                 Oro\Bundle\AttachmentBundle\DataGrid\Action\DialogAction

    oro_attachment.provider.attachment.class:                    Oro\Bundle\AttachmentBundle\Provider\AttachmentProvider

    oro_attachment.formatter.image_encoded.class:                Oro\Bundle\AttachmentBundle\Formatter\ImageEncodedFormatter
    oro_attachment.formatter.image_link.class:                   Oro\Bundle\AttachmentBundle\Formatter\ImageLinkFormatter
    oro_attachment.formatter.image_src.class:                    Oro\Bundle\AttachmentBundle\Formatter\ImageSrcFormatter

    oro_attachment.attachments_dir:                              attachment
    oro_attachment.media_cache_dir:                              media/cache

    oro_attachment.filesystem_name.attachment:                   attachments
    oro_attachment.filesystem_name.mediacache:                   mediacache
    oro_attachment.filesystem_name.protected_mediacache:         protected_mediacache

    oro_attachment.filesystem_dir.protected_mediacache:          attachment/cache

    liip_imagine.meta_data.reader.class:                         Imagine\Image\Metadata\DefaultMetadataReader

    oro_attachment.liip_imagine.unsupported_mime_types:          ['image/svg+xml']

    oro_attachment.provider.resized_image_path.skip_prefix:      'media/cache'

services:
    oro_attachment.manager:
        class: '%oro_attachment.manager.attachment_manager.class%'
        arguments:
            - '@router'
            - '%oro_attachment.files%'
            - '@oro_entity_extend.association_manager'
            - '%kernel.debug%'
            - '%oro_attachment.debug_images%'
        calls:
            - [setFileManager, ['@oro_attachment.file_manager']]
            - [setFileUrlProvider, ['@oro_attachment.provider.file_url']]

    oro_attachment.file_manager:
        class: Oro\Bundle\AttachmentBundle\Manager\FileManager
        arguments:
          - '@knp_gaufrette.filesystem_map'
          - '@oro_attachment.protocol_validator'
        lazy: true

    oro_attachment.protocol_validator:
        class: Oro\Bundle\AttachmentBundle\Validator\ProtocolValidator
        public: false

    oro_attachment.mime_type_validator:
        class: Oro\Bundle\AttachmentBundle\Validator\Constraints\MimeTypeValidator
        public: false
        arguments:
            - '%oro_attachment.upload_file_mime_types%'
            - '%oro_attachment.upload_image_mime_types%'
        tags:
            - { name: validator.constraint_validator }

    oro_attachment.validators.image_validator:
        class: 'Oro\Bundle\AttachmentBundle\Validator\Constraints\ImageValidator'
        arguments:
            - '@oro_config.global'
        tags:
            - { name: validator.constraint_validator, alias: oro_attachment_image_validator }

    oro_attachment.liip_imagine.binary.factory.guess_mime_type:
        class: 'Oro\Bundle\AttachmentBundle\Tools\Imagine\Binary\Factory\GuessMimeType\GuessMimeTypeByFileContextFactory'
        arguments:
          - '@liip_imagine.binary.mime_type_guesser'
          - '@liip_imagine.extension_guesser'

    oro_attachment.liip_imagine.binary.filter:
        class: 'Oro\Bundle\AttachmentBundle\Tools\Imagine\Binary\Filter\Basic\BasicImagineBinaryFilter'
        arguments:
          - '@liip_imagine.filter.manager'

    oro_attachment.liip_imagine.binary.filter.unsupported_binaries.skip_by_mime_type:
       class: 'Oro\Bundle\AttachmentBundle\Tools\Imagine\Binary\Filter\UnsupportedBinaries\SkipUnsupportedBinariesByMimeTypeFilterDecorator'
       decorates: oro_attachment.liip_imagine.binary.filter
       decoration_priority: 10
       arguments:
          - '@oro_attachment.liip_imagine.binary.filter.unsupported_binaries.skip_by_mime_type.inner'
          - '%oro_attachment.liip_imagine.unsupported_mime_types%'

    oro_attachment.thumbnail_factory:
        class: Oro\Bundle\AttachmentBundle\Tools\ThumbnailFactory
        arguments:
          - '@oro_attachment.liip_imagine.binary.factory.guess_mime_type'
          - '@oro_attachment.liip_imagine.binary.filter'
          - '@liip_imagine.filter.configuration'

    oro_attachment.association_helper:
        class: Oro\Bundle\AttachmentBundle\Tools\AttachmentAssociationHelper
        public: false
        arguments:
            - '@oro_entity_config.config_manager'

    oro_attachment.manager.api:
        class: '%oro_attachment.manager.api.class%'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%oro_attachment.entity.class%'
            - '@doctrine.orm.entity_manager'
            - '@security.authorization_checker'
            - '@oro_attachment.manager'
            - '@oro_entity.doctrine_helper'

    oro_attachment.manager.file.api:
        class: '%oro_attachment.manager.file.api.class%'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%oro_attachment.file.entity.class%'
            - '@doctrine.orm.entity_manager'
            - '@security.authorization_checker'
            - '@oro_attachment.file_manager'
            - '@oro_attachment.manager'

    oro_attachment.listener.file_listener:
        class: Oro\Bundle\AttachmentBundle\EventListener\FileListener
        arguments:
            - '@oro_attachment.file_manager'
            - '@oro_security.token_accessor'
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%oro_attachment.file.entity.class%', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: '%oro_attachment.file.entity.class%', event: preUpdate }
            - { name: doctrine.orm.entity_listener, entity: '%oro_attachment.file.entity.class%', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: '%oro_attachment.file.entity.class%', event: postUpdate }

    oro_attachment.twig.file_extension:
        class: Oro\Bundle\AttachmentBundle\Twig\FileExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    oro_attachment.entity_config_dumper.extension.file:
        class: '%oro_attachment.entity_config_dumper.extension.file.class%'
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_entity_extend.relation_builder'
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_attachment.entity_config_dumper.extension:
        class: '%oro_attachment.entity_config_dumper.extension.class%'
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_attachment.entity_generator.extension:
        class: '%oro_attachment.entity_generator.extension.class%'
        tags:
            - { name: oro_entity_extend.entity_generator_extension }


    oro_attachment.migration.extension.attachment:
        class: '%oro_attachment.migration.extension.attachment.class%'
        tags:
            - { name: oro_migration.extension, extension_name: attachment }

    oro_attachment.serializer.file_normalizer:
        class: '%oro_attachment.serializer.file_normalizer.class%'
        calls:
            - [setAttachmentManager, ['@oro_attachment.manager']]
            - [setFileManager, ['@oro_attachment.file_manager']]
            - [setValidator, ['@oro_attachment.validator.file_config_validator']]
            - [setLogger, ['@logger']]
        tags:
            - { name: oro_importexport.normalizer}

    oro_attachment.placeholder.filter:
        class: '%oro_attachment.placeholder.filter.class%'
        arguments:
            - '@oro_attachment.association_helper'
            - '@oro_entity.doctrine_helper'

    oro_attachment.event_listener.attachment_grid_listener:
        class: '%oro_attachment.attachment_grid_listener%'
        arguments:
            - [entityId]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.attachment-grid, method: onBuildAfter }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.attachment-grid, method: onBuildBefore }

    oro_attachment.listener.merge_listener:
        class: Oro\Bundle\AttachmentBundle\EventListener\MergeListener
        arguments:
            - '@oro_attachment.manager'
        tags:
            - { name: kernel.event_listener, event: oro.entity_merge.build_metadata, method: onBuildMetadata }

    oro_attachment.datagrid.action.dialog:
        class: '%oro_attachment.datagrid.action.dialog.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: dialog }

    oro_attachment.widget_provider.actions:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - oro_add_attachment_button
            - oro_add_attachment_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: -90 }
            - { name: oro_ui.update_action_provider, group: activity, priority: -90 }

    oro_attachment.provider.attachment:
        class: '%oro_attachment.provider.attachment.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_attachment.association_helper'
            - '@oro_attachment.manager'

    oro_attachment.exclusion_provider:
        class: Oro\Bundle\AttachmentBundle\Provider\AttachmentExclusionProvider
        public: false
        tags:
            - { name: oro_entity.exclusion_provider.api }

    oro_attachment.formatter.image_encoded:
        class: '%oro_attachment.formatter.image_encoded.class%'
        arguments:
          - '@oro_attachment.file_manager'
          - '@file_locator'
        tags:
          - { name: oro_formatter, formatter: image_encoded }

    oro_attachment.formatter.image_link:
        class: '%oro_attachment.formatter.image_link.class%'
        arguments:
          - '@oro_attachment.manager'
          - '@translator'
        tags:
          - { name: oro_formatter, formatter: image_link }

    oro_attachment.formatter.image_src:
        class: '%oro_attachment.formatter.image_src.class%'
        arguments:
          - '@oro_attachment.manager'
        tags:
          - { name: oro_formatter, formatter: image_src }

    oro_attachment.image_resizer:
        class: 'Oro\Bundle\AttachmentBundle\Resizer\ImageResizer'
        arguments:
            - '@oro_attachment.file_manager'
            - '@oro_attachment.liip_imagine.binary.factory.guess_mime_type'
            - '@oro_attachment.liip_imagine.binary.filter'
        calls:
            - [setLogger, ['@logger']]

    oro_attachment.media_cache_manager:
        class: 'Oro\Bundle\AttachmentBundle\Manager\MediaCacheManager'
        parent: 'oro_gaufrette.file_manager'
        arguments:
            - 'mediacache'
            - '%oro_attachment.media_cache_dir%'

    oro_attachment.manager.protected_mediacache:
        parent: 'oro_gaufrette.file_manager'
        public: true
        arguments:
            - '%oro_attachment.filesystem_name.protected_mediacache%'

    oro_attachment.manager.media_cache_manager_registry:
        class: 'Oro\Bundle\AttachmentBundle\Manager\MediaCacheManagerRegistry'
        arguments:
            - '@oro_attachment.acl.file_access_control_checker'
            - '@oro_attachment.media_cache_manager'
            - '@oro_attachment.manager.protected_mediacache'

    oro_attachment.event_listener.sets_parent_entity_on_flush:
        class: 'Oro\Bundle\AttachmentBundle\EventListener\SetsParentEntityOnFlushListener'
        arguments:
            - '@property_accessor'
        tags:
            - { name: doctrine.event_listener, event: onFlush, connection: default }
            - { name: doctrine.event_listener, event: prePersist, connection: default }
            - { name: doctrine.event_listener, event: postPersist, connection: default }

    oro_attachment.acl.voter.file:
        class: 'Oro\Bundle\AttachmentBundle\Acl\Voter\FileVoter'
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_attachment.acl.file_access_control_checker'
            - '@oro_attachment.provider.file_applications'
            - '@oro_action.provider.current_application'
            - '@security.authorization_checker'
            - '@oro_security.token_accessor'
        calls:
            - [setClassName, ['%oro_attachment.file.entity.class%']]
        tags:
            - { name: security.voter }

    oro_attachment.acl.file_access_control_checker:
        class: 'Oro\Bundle\AttachmentBundle\Acl\FileAccessControlChecker'
        public: false
        arguments:
            - '@oro_entity_config.config_manager'

    oro_attachment.url_generator:
        class: Oro\Bundle\AttachmentBundle\Provider\AttachmentFilterAwareUrlGenerator
        arguments:
            - '@router'
            - '@liip_imagine.filter.configuration'

    oro_attachment.provider.attachment_file_name_provider:
        class: Oro\Bundle\AttachmentBundle\Provider\AttachmentFileNameProvider
        public: true

    oro_attachment.provider.file_url:
        class: 'Oro\Bundle\AttachmentBundle\Provider\FileUrlProvider'
        arguments:
            - '@oro_attachment.url_generator'
        calls:
            - ['setFilenameProvider', ['@oro_attachment.provider.attachment_file_name_provider']]

    oro_attachment.provider.resized_image_path:
        class: 'Oro\Bundle\AttachmentBundle\Provider\ResizedImagePathProvider'
        arguments:
            - '@oro_attachment.provider.file_url'

    oro_attachment.provider.resized_image_path.base_url:
        class: 'Oro\Bundle\AttachmentBundle\Provider\ResizedImagePathProviderDecorator'
        decorates: oro_attachment.provider.resized_image_path
        decoration_priority: 300
        arguments:
            - '@oro_attachment.provider.resized_image_path.base_url.inner'
            - '@=service("router").getContext().getBaseUrl()'

    oro_attachment.provider.resized_image_path.skip_prefix:
        class: 'Oro\Bundle\AttachmentBundle\Provider\ResizedImagePathProviderDecorator'
        decorates: oro_attachment.provider.resized_image_path
        decoration_priority: 200
        arguments:
            - '@oro_attachment.provider.resized_image_path.skip_prefix.inner'
            - '%oro_attachment.provider.resized_image_path.skip_prefix%'

    oro_attachment.manager.image_resize:
        class: 'Oro\Bundle\AttachmentBundle\Manager\ImageResizeManager'
        arguments:
            - '@oro_attachment.image_resizer'
            - '@oro_attachment.thumbnail_factory'
            - '@oro_attachment.provider.resized_image_path'
            - '@oro_attachment.manager.media_cache_manager_registry'
            - '@oro_attachment.liip_imagine.binary.factory.guess_mime_type'
            - '@oro_attachment.file_manager'

    oro_attachment.provider.file_applications:
        class: 'Oro\Bundle\AttachmentBundle\Provider\FileApplicationsProvider'
        public: false
        arguments:
            - '@oro_entity_config.config_manager'

    oro_attachment.api.processor.file_view_security_check:
        class: Oro\Bundle\AttachmentBundle\Api\Processor\FileViewSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
        tags:
            - { name: oro.api.processor, action: get, group: data_security_check, class: '%oro_attachment.file.entity.class%', priority: 10 }

    oro_attachment.filtered_attachment_migration:
        class: 'Oro\Bundle\AttachmentBundle\Migration\FilteredAttachmentMigrationService'
        public: true
        arguments:
            - '@knp_gaufrette.filesystem_map'
            - '@liip_imagine.filter.configuration'
            - '@oro_layout.loader.image_filter'
            - '%oro_attachment.filesystem_name.mediacache%'
        calls:
            - ['setWorkingDirectory', ['%kernel.project_dir%/public/%oro_attachment.media_cache_dir%']]

    oro_attachment.api.processor.files_view_security_check:
        class: Oro\Bundle\AttachmentBundle\Api\Processor\FilesViewSecurityCheck
        arguments:
            - '@oro_api.security.authorization_checker'
        tags:
            - { name: oro.api.processor, action: get_list, group: data_security_check, class: '%oro_attachment.file.entity.class%', priority: 10 }

    oro_attachment.liip_imagine.filter.loader.watermark:
        class: Liip\ImagineBundle\Imagine\Filter\Loader\WatermarkFilterLoader
        decorates: liip_imagine.filter.loader.watermark
        arguments:
            - '@liip_imagine'
            - 'gaufrette:/' # One slash instead of two used intentionally due to specifics of WatermarkFilterLoader

    oro_attachment.manager.image_removal_manager:
        class: Oro\Bundle\AttachmentBundle\Manager\ImageRemovalManager
        arguments:
            - '@oro_attachment.file_manager'
            - '@oro_config.manager'
            - '@liip_imagine.filter.configuration'
            - '@oro_attachment.provider.resized_image_path'
            - '@filesystem'
            - '@knp_gaufrette.filesystem_map'
            - '%oro_attachment.filesystem_name.mediacache%'
            - 'public/%oro_attachment.media_cache_dir%'
            - '%kernel.project_dir%'

    oro_attachment.message_processor.image_remove:
        class: Oro\Bundle\AttachmentBundle\MessageProcessor\ImageRemoveMessageProcessor
        arguments:
            - '@logger'
            - '@oro_attachment.manager.image_removal_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
