entity_config:
    grid:
        entity:
            items:
                # default grid name for the entity
                default: # string
                    options:
                        auditable:          false

    entity:
        entity:
            items:
                grid_all_view_label:
                    options:
                        translatable:       true
                        priority:           40
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            60
