services:
    oro_locale.settings:
        class: Oro\Bundle\LocaleBundle\Model\LocaleSettings
        public: true
        arguments:
            - '@oro_config.manager'
            - '@oro_locale.calendar_factory'
            - '@oro_locale.manager.localization'
            - '@oro_locale.configuration_provider'

    Oro\Bundle\LocaleBundle\Model\LocaleSettings:
        alias: 'oro_locale.settings'

    oro_locale.configuration_provider:
        class: Oro\Bundle\LocaleBundle\Configuration\LocaleConfigurationProvider
        arguments:
            - '@oro_locale.name_format_configuration.provider'
            - '@oro_locale.address_format_configuration.provider'
            - '@oro_locale.locale_data_configuration.provider'

    oro_locale.name_format_configuration.provider:
        class: Oro\Bundle\LocaleBundle\Configuration\NameFormatConfigurationProvider
        parent: oro.static_config_provider.abstract
        arguments:
            - '%kernel.cache_dir%/oro/locale_name_format.php'
            - '%kernel.debug%'

    oro_locale.address_format_configuration.provider:
        class: Oro\Bundle\LocaleBundle\Configuration\AddressFormatConfigurationProvider
        parent: oro.static_config_provider.abstract
        arguments:
            - '%kernel.cache_dir%/oro/locale_address_format.php'
            - '%kernel.debug%'

    oro_locale.locale_data_configuration.provider:
        class: Oro\Bundle\LocaleBundle\Configuration\LocaleDataConfigurationProvider
        parent: oro.static_config_provider.abstract
        arguments:
            - '%kernel.cache_dir%/oro/locale_data.php'
            - '%kernel.debug%'

    oro_locale.helper.localization:
        class: Oro\Bundle\LocaleBundle\Helper\LocalizationHelper
        arguments:
            - '@oro_locale.manager.localization'
            - '@oro_locale.provider.current_localization'

    Oro\Bundle\LocaleBundle\Helper\LocalizationHelper:
        alias: oro_locale.helper.localization

    oro_locale.helper.default_locale_localization:
        class: Oro\Bundle\LocaleBundle\Helper\LocalizationHelper
        arguments:
           - '@oro_locale.manager.localization'
           - '@oro_locale.provider.config_default_localization'

    oro_locale.helper.localization.link:
        tags:
            - { name: oro_service_link, service: oro_locale.helper.localization }

    oro_locale.listener.orm.localization_listener:
        class: Oro\Bundle\LocaleBundle\EventListener\ORM\LocalizationListener
        arguments:
            - '@oro_locale.translation.strategy.localization_fallback_strategy'
            - '@oro_locale.manager.localization'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\LocaleBundle\Entity\Localization', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\LocaleBundle\Entity\Localization', event: postUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\LocaleBundle\Entity\Localization', event: postRemove }

    oro_locale.datagrid.extension.localized_value:
        class: Oro\Bundle\LocaleBundle\Datagrid\Extension\LocalizedValueExtension
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity.orm.entity_class_resolver'
            - '@oro_locale.helper.localization'
        tags:
            - { name: oro_datagrid.extension }

    oro_locale.datagird.formatter.localized_value_property:
        class: Oro\Bundle\LocaleBundle\Datagrid\Formatter\Property\LocalizedValueProperty
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: localized_value }

    oro_locale.translation.strategy.localization_fallback_strategy:
        class: Oro\Bundle\LocaleBundle\Translation\Strategy\LocalizationFallbackStrategy
        arguments:
            - '@doctrine'
            - '@oro_locale.cache.provider.tree_fallback_strategy'
        calls:
            - [setEntityClass, ['Oro\Bundle\LocaleBundle\Entity\Localization']]
        tags:
            - { name: kernel.cache_warmer }

    # Calendar
    oro_locale.calendar:
        shared: false
        public: true
        class: Oro\Bundle\LocaleBundle\Model\Calendar

    oro_locale.calendar_factory:
        class: Oro\Bundle\LocaleBundle\Model\CalendarFactory
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: container.service_subscriber, id: 'oro_locale.calendar' }

    # Converters
    oro_locale.format_converter.date_time.registry:
        class: Oro\Bundle\LocaleBundle\Converter\DateTimeFormatConverterRegistry
        arguments:
            - [] # converter names
            - ~ # service locator for converters

    oro_locale.format_converter.date_time.intl:
        class: Oro\Bundle\LocaleBundle\Converter\IntlDateTimeFormatConverter
        arguments:
            - '@oro_locale.formatter.date_time'
            - '@translator'
        tags:
            - { name: oro_locale.format_converter.date_time, alias: intl }

    oro_locale.format_converter.date_time.moment:
        class: Oro\Bundle\LocaleBundle\Converter\MomentDateTimeFormatConverter
        arguments:
            - '@oro_locale.formatter.date_time'
            - '@translator'
        tags:
            - { name: oro_locale.format_converter.date_time, alias: moment }

    oro_locale.format_converter.date_time.php:
        class: Oro\Bundle\LocaleBundle\Converter\PhpDateTimeFormatConverter
        arguments:
            - '@oro_locale.formatter.date_time'
            - '@translator'
        tags:
            - { name: oro_locale.format_converter.date_time, alias: php }

    # event listeners
    oro_locale.locale_listener:
        class: Oro\Bundle\LocaleBundle\EventListener\LocaleListener
        arguments:
            - '@oro_locale.settings'
            - '@oro_locale.provider.current_localization'
            - '@stof_doctrine_extensions.listener.translatable'
            - '@translator'
            - '@router'
            - '%installed%'
        tags:
            - { name: kernel.event_subscriber }

    # Formatters
    oro_locale.formatter.name:
        class: Oro\Bundle\LocaleBundle\Formatter\NameFormatter
        arguments:
            - '@oro_locale.settings'

    oro_locale.formatter.name.link:
        tags:
            - { name: oro_service_link, service: oro_locale.formatter.name }

    oro_locale.formatter.address:
        class: Oro\Bundle\LocaleBundle\Formatter\AddressFormatter
        arguments:
            - '@oro_locale.settings'
            - '@oro_locale.formatter.name'
            - '@property_accessor'
        calls:
            - [setPhoneProvider, ['@oro_address.provider.phone']]

    oro_locale.formatter.date_time:
        class: Oro\Bundle\LocaleBundle\Formatter\DateTimeFormatter
        public: true
        arguments:
            - '@oro_locale.settings'
            - '@translator'

    oro_locale.formatter.number:
        class: Oro\Bundle\LocaleBundle\Formatter\NumberFormatter
        public: true
        arguments:
            - '@oro_locale.settings'

    # DQL formatter
    oro_locale.dql.formatter.name:
        class: Oro\Bundle\LocaleBundle\DQL\DQLNameFormatter
        arguments:
            - '@oro_locale.formatter.name'

    oro_locale.dql.formatter.name.link:
        tags:
            - { name: oro_service_link, service: oro_locale.dql.formatter.name }

    oro_locale.formatter.language_code:
        class: Oro\Bundle\LocaleBundle\Formatter\LanguageCodeFormatter
        public: true
        arguments:
            - '@translator'
            - '@oro_locale.settings'

    oro_locale.formatter.formatting_code:
        class: Oro\Bundle\LocaleBundle\Formatter\FormattingCodeFormatter
        arguments:
            - '@translator'
            - '@oro_locale.settings'

    # Twig extensions
    oro_locale.twig.date_format:
        class: Oro\Bundle\LocaleBundle\Twig\DateFormatExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.locale:
        class: Oro\Bundle\LocaleBundle\Twig\LocaleExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.calendar:
        class: Oro\Bundle\LocaleBundle\Twig\CalendarExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.date_time:
        class: Oro\Bundle\LocaleBundle\Twig\DateTimeExtension
        public: true
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.address:
        class: Oro\Bundle\LocaleBundle\Twig\AddressExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.number:
        class: Oro\Bundle\LocaleBundle\Twig\NumberExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.twig.localization:
        class: Oro\Bundle\LocaleBundle\Twig\LocalizationExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_locale.format.datetime:
        class: Oro\Bundle\LocaleBundle\Formatter\DateTimeValueFormatter
        arguments:
            - '@oro_locale.formatter.date_time'
            - '@translator'
        tags:
            - { name: oro_formatter, formatter: datetime, data_type: datetime }

    oro_locale.format.date:
        class: Oro\Bundle\LocaleBundle\Formatter\DateValueFormatter
        arguments:
            - '@oro_locale.formatter.date_time'
            - '@translator'
        tags:
            - { name: oro_formatter, formatter: date, data_type: date }

    oro_locale.format.currency:
        class: Oro\Bundle\LocaleBundle\Formatter\CurrencyFormatter
        arguments:
            - '@oro_locale.formatter.number'
        tags:
            - { name: oro_formatter, formatter: currency, data_type: money }

    oro_locale.entity_name_provider:
        class: Oro\Bundle\LocaleBundle\Provider\EntityNameProvider
        arguments:
            - '@oro_locale.formatter.name.link'
            - '@oro_locale.dql.formatter.name.link'
        tags:
            - { name: oro_entity.name_provider, priority: -80 }

    oro_locale.validator.localization:
        class: Oro\Bundle\LocaleBundle\Validator\Constraints\LocalizationValidator
        public: true
        tags:
            - { name: validator.constraint_validator, alias: oro_locale.localization_validator }

    oro_locale.validator.default_localization:
        class: Oro\Bundle\LocaleBundle\Validator\Constraints\DefaultLocalizationValidator
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: validator.constraint_validator, alias: oro_locale.default_localization_validator }

    oro_locale.acl.voter.localization:
        class: Oro\Bundle\LocaleBundle\Acl\Voter\LocalizationVoter
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_config.manager'
        calls:
            - [setClassName, ['Oro\Bundle\LocaleBundle\Entity\Localization']]
        tags:
            - { name: security.voter }

    oro_locale.repository.localization:
        class: Oro\Bundle\LocaleBundle\Entity\Repository\LocalizationRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\LocaleBundle\Entity\Localization'

    oro_locale.provider.localization_choices:
        class: Oro\Bundle\LocaleBundle\Provider\LocalizationChoicesProvider
        public: true
        arguments:
            - '@oro_locale.settings'
            - '@oro_locale.formatter.language_code'
            - '@oro_translation.provider.language'
            - '@oro_locale.manager.localization'

    oro_locale.manager.localization:
        class: Oro\Bundle\LocaleBundle\Manager\LocalizationManager
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_config.manager'
            - '@oro.cache.memory_cache_chain'

    oro_locale.provider.current_localization:
        class: Oro\Bundle\LocaleBundle\Provider\CurrentLocalizationProvider
        arguments:
            - !tagged_iterator oro_locale.extension.current_localization

    oro_locale.provider.config_default_localization:
        class: Oro\Bundle\LocaleBundle\Provider\ConfigDefaultLocalizationProvider
        arguments:
            - '@oro_locale.manager.localization'

    oro_locale.entity_generator.extension:
        class: Oro\Bundle\LocaleBundle\Tools\GeneratorExtensions\DefaultFallbackGeneratorExtension
        arguments:
            - [] # a map of default fallback fields
        tags:
            - { name: oro_entity_extend.entity_generator_extension, priority: 255 }

    oro_locale.twig.date_time_organization:
        class: Oro\Bundle\LocaleBundle\Twig\DateTimeOrganizationExtension
        parent: oro_locale.twig.date_time
        deprecated: The "%service_id%" service is deprecated since 1.11, will be removed after 1.13.
        tags:
            - { name: twig.extension }

    oro_locale.layout.data_provider.locale:
        class: Oro\Bundle\LocaleBundle\Layout\LocaleProvider
        arguments:
            - '@oro_locale.helper.localization'
        tags:
            - { name: layout.data_provider, alias: locale }

    oro_locale.localization_scope_criteria_provider:
        class: Oro\Bundle\LocaleBundle\Provider\LocalizationScopeCriteriaProvider
        arguments:
            - "@oro_locale.provider.current_localization"
        tags:
            - { name: oro_scope.provider, scopeType: web_content, priority: 1 }

    oro_locale.provider.preferred_localization_provider:
        class: Oro\Bundle\LocaleBundle\Provider\ChainPreferredLocalizationProvider
        arguments:
            - !tagged_iterator oro_locale.preferred_localization_provider

    Oro\Bundle\LocaleBundle\Provider\PreferredLocalizationProviderInterface:
        alias: 'oro_locale.provider.preferred_localization_provider'
        public: true

    # Application default localization
    # This provider should be called last
    oro_locale.provider.preferred_localization_provider.default:
        class: Oro\Bundle\LocaleBundle\Provider\DefaultPreferredLocalizationProvider
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: oro_locale.preferred_localization_provider, priority: -255 }

    oro_locale_config.event_listener.localization_change:
        class: Oro\Bundle\LocaleBundle\EventListener\LocalizationChangeListener
        arguments:
            - '@oro_config.user'
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oro_config.update_after, method: onConfigUpdate }

    oro_locale.datagrid.event_listener.enabled_localizations_grid:
        class: Oro\Bundle\LocaleBundle\Datagrid\EventListener\EnabledLocalizationsGridListener
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.enabled-localizations-select-grid, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.enabled-localizations-select-grid, method: onBuildAfter }

    oro_locale.autocomplete.enabled_localizations.search_handler:
        parent: oro_form.autocomplete.search_handler
        class: Oro\Bundle\LocaleBundle\Autocomplete\EnabledLocalizationsSearchHandler
        arguments:
            - 'Oro\Bundle\LocaleBundle\Entity\Localization'
            - ['name']
            - '@oro_config.manager'
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: oro_enabled_localization, acl_resource: oro_locale_localization_view }
