services:
    oro_datagrid.extension.action.factory:
        class: Oro\Bundle\DataGridBundle\Extension\Action\ActionFactory
        arguments:
            - ~ # service locator for actions

    oro_datagrid.extension.action.metadata_factory:
        class: Oro\Bundle\DataGridBundle\Extension\Action\ActionMetadataFactory
        arguments:
            - '@translator'

    oro_datagrid.extension.action.type.navigate:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\NavigateAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: navigate }

    oro_datagrid.extension.action.type.ajax:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\AjaxAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: ajax }

    oro_datagrid.extension.action.type.delete:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\DeleteAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: delete }

    oro_datagrid.extension.action.type.ajaxdelete:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\AjaxDeleteAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: ajaxdelete }

    oro_datagrid.extension.action.type.frontend:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\FrontendAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: frontend }

    oro_datagrid.extension.action.type.import:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\ImportAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: import }

    oro_datagrid.extension.action.type.export:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\ExportAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: export }

    oro_datagrid.extension.action.type.trigger_event:
        class: Oro\Bundle\DataGridBundle\Extension\Action\Actions\TriggerEventAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: trigger-event }
