parameters:
    oro_datagrid.importexport.data_converter.class:             Oro\Bundle\DataGridBundle\ImportExport\DatagridDataConverter
    oro_datagrid.importexport.export_reader.class:              Oro\Bundle\DataGridBundle\ImportExport\DatagridExportReader
    oro_datagrid.importexport.export_connector.class:           Oro\Bundle\DataGridBundle\ImportExport\DatagridExportConnector

services:
    oro_datagrid.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
             - [setDataConverter, ['@oro_datagrid.importexport.data_converter']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: datagrid, alias: oro_datagrid }

    oro_datagrid.importexport.data_converter:
        class: '%oro_datagrid.importexport.data_converter.class%'
        lazy: true
        arguments:
            - '@oro_datagrid.importexport.datagrid_columns_from_context_provider'
            - '@translator'
            - '@oro_importexport.formatter.formatter_provider'

    oro_datagrid.importexport.export_reader:
        class: '%oro_datagrid.importexport.export_reader.class%'
        arguments:
            - '@oro_importexport.context_registry'
            - '@oro_datagrid.importexport.export_connector'

    oro_datagrid.importexport.export_filtered_reader:
        class: Oro\Bundle\DataGridBundle\ImportExport\FilteredEntityReader
        arguments:
            - '@oro_datagrid.datagrid.manager'
            - '@oro_security.acl_helper'
            - '@oro_importexport.reader.entity'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]

    oro_datagrid.importexport.export_connector:
        class: '%oro_datagrid.importexport.export_connector.class%'
        arguments:
            - '@oro_datagrid.datagrid.manager.link'

    oro_datagrid.importexport.export_id_fetcher:
        class: Oro\Bundle\DataGridBundle\ImportExport\DatagridExportIdFetcher
        arguments:
            - '@oro_datagrid.datagrid.manager.link'
            - '@event_dispatcher'
        calls:
            - [setQueryExecutor, ['@oro_datagrid.orm.query_executor']]

    oro_datagrid.importexport.datagrid_columns_from_context_provider:
        class: 'Oro\Bundle\DataGridBundle\ImportExport\DatagridColumnsFromContextProvider'
        lazy: true
        arguments:
        - '@oro_datagrid.datagrid.manager'
        - '@oro_datagrid.provider.state.columns'
