aliases:
    backbone-pageable-collection$: npmassets/@oroinc/backbone.pageable/lib/backbone-pageable
    backgrid$: orodatagrid/js/extend/backgrid
    oro/datagrid/action/abstract-action$: orodatagrid/js/datagrid/action/abstract-action
    oro/datagrid/action/ajax-action$: orodatagrid/js/datagrid/action/ajax-action
    oro/datagrid/action/ajaxdelete-action$: orodatagrid/js/datagrid/action/ajaxdelete-action
    oro/datagrid/action/delete-action$: orodatagrid/js/datagrid/action/delete-action
    oro/datagrid/action/delete-mass-action$: orodatagrid/js/datagrid/action/delete-mass-action
    oro/datagrid/action/dialog-action$: orodatagrid/js/datagrid/action/dialog-action
    oro/datagrid/action/edit-mass-action$: orodatagrid/js/datagrid/action/edit-mass-action
    oro/datagrid/action/export-action$: orodatagrid/js/datagrid/action/export-action
    oro/datagrid/action/frontend-action$: orodatagrid/js/datagrid/action/frontend-action
    oro/datagrid/action/frontend-mass-action$: orodatagrid/js/datagrid/action/frontend-mass-action
    oro/datagrid/action/mass-action$: orodatagrid/js/datagrid/action/mass-action
    oro/datagrid/action/model-action$: orodatagrid/js/datagrid/action/model-action
    oro/datagrid/action/navigate-action$: orodatagrid/js/datagrid/action/navigate-action
    oro/datagrid/action/refresh-collection-action$: orodatagrid/js/datagrid/action/refresh-collection-action
    oro/datagrid/action/reset-collection-action$: orodatagrid/js/datagrid/action/reset-collection-action
    oro/datagrid/action/row/importexport-action$: orodatagrid/js/datagrid/action/row/importexport-action
    oro/datagrid/action/select-data-appearance-action$: orodatagrid/js/datagrid/action/select-data-appearance-action
    oro/datagrid/action/show-component-action$: orodatagrid/js/datagrid/action/show-component-action
    oro/datagrid/action/trigger-event-action$: orodatagrid/js/datagrid/action/trigger-event-action
    oro/datagrid/cell/action-cell$: orodatagrid/js/datagrid/cell/action-cell
    oro/datagrid/cell/boolean-cell$: orodatagrid/js/datagrid/cell/boolean-cell
    oro/datagrid/cell/date-cell$: orodatagrid/js/datagrid/cell/date-cell
    oro/datagrid/cell/datetime-cell$: orodatagrid/js/datagrid/cell/datetime-cell
    oro/datagrid/cell/html-cell$: orodatagrid/js/datagrid/cell/html-cell
    oro/datagrid/cell/multi-relation-cell$: orodatagrid/js/datagrid/cell/multi-relation-cell
    oro/datagrid/cell/multi-select-cell$: orodatagrid/js/datagrid/cell/multi-select-cell
    oro/datagrid/cell/number-cell$: orodatagrid/js/datagrid/cell/number-cell
    oro/datagrid/cell/phone-cell$: orodatagrid/js/datagrid/cell/phone-cell
    oro/datagrid/cell/relation-cell$: orodatagrid/js/datagrid/cell/relation-cell
    oro/datagrid/cell/select-cell$: orodatagrid/js/datagrid/cell/select-cell
    oro/datagrid/cell/select-row-cell$: orodatagrid/js/datagrid/cell/select-row-cell
    oro/datagrid/cell/string-cell$: orodatagrid/js/datagrid/cell/string-cell
    oro/datagrid/cell/time-cell$: orodatagrid/js/datagrid/cell/time-cell
configs:
    orodatagrid/js/app/plugins/grid/datagrid-settings-plugin: {}
    orodatagrid/js/app/plugins/grid/toolbar-mass-action-plugin: {}
    orodatagrid/js/app/views/datagrid-settings-list/datagrid-settings-list-collection-view: {}
    orodatagrid/js/app/views/grid/datagrid-module-manager-view: {}
    orodatagrid/js/datagrid/action-launcher: {}
    orodatagrid/js/datagrid/cell/action-cell: {}
    orodatagrid/js/datagrid/dropdown-select-choice-launcher: {}
    orodatagrid/js/datagrid/grid-views/model: {}
    orodatagrid/js/datagrid/grid-views/view: {}
    orodatagrid/js/datagrid/sorting/dropdown: {}
    orodatagrid/js/grid-views-builder: {}
dynamic-imports:
    orodatagrid:
        - oro/datagrid/action/abstract-action
        - oro/datagrid/action/ajax-action
        - oro/datagrid/action/ajaxdelete-action
        - oro/datagrid/action/delete-action
        - oro/datagrid/action/delete-mass-action
        - oro/datagrid/action/dialog-action
        - oro/datagrid/action/edit-mass-action
        - oro/datagrid/action/export-action
        - oro/datagrid/action/frontend-action
        - oro/datagrid/action/frontend-mass-action
        - oro/datagrid/action/mass-action
        - oro/datagrid/action/model-action
        - oro/datagrid/action/navigate-action
        - oro/datagrid/action/refresh-collection-action
        - oro/datagrid/action/reset-collection-action
        - oro/datagrid/action/row/importexport-action
        - oro/datagrid/action/select-data-appearance-action
        - oro/datagrid/action/show-component-action
        - oro/datagrid/action/trigger-event-action
        - oro/datagrid/cell/action-cell
        - oro/datagrid/cell/boolean-cell
        - oro/datagrid/cell/date-cell
        - oro/datagrid/cell/datetime-cell
        - oro/datagrid/cell/html-cell
        - oro/datagrid/cell/multi-relation-cell
        - oro/datagrid/cell/multi-select-cell
        - oro/datagrid/cell/number-cell
        - oro/datagrid/cell/phone-cell
        - oro/datagrid/cell/relation-cell
        - oro/datagrid/cell/select-cell
        - oro/datagrid/cell/select-row-cell
        - oro/datagrid/cell/string-cell
        - oro/datagrid/cell/time-cell
        - orodatagrid/js/app/components/cell-popup-editor-component
        - orodatagrid/js/app/components/column-renderer-component
        - orodatagrid/js/app/components/datagrid-allow-tracking-component
        - orodatagrid/js/app/components/datagrid-component
        - orodatagrid/js/app/components/grid-sidebar-component
        - orodatagrid/js/app/components/multi-grid-component
        - orodatagrid/js/app/plugins/grid-component/board-appearance-plugin
        - orodatagrid/js/app/plugins/grid/inline-editing-plugin
        - orodatagrid/js/app/transitions/update-main-property-transition
        - orodatagrid/js/app/views/board/board-view
        - orodatagrid/js/app/views/board/card-view
        - orodatagrid/js/app/views/board/column-header-view
        - orodatagrid/js/app/views/board/column-view
        - orodatagrid/js/appearance/builder
        - orodatagrid/js/datagrid/listener/action-form-listener
        - orodatagrid/js/datagrid/listener/callback-listener
        - orodatagrid/js/datagrid/listener/change-editable-cell-listener
        - orodatagrid/js/datagrid/listener/column-form-listener
        - orodatagrid/js/grid-views-builder
        - orodatagrid/js/inline-editing/builder
        - orodatagrid/js/inline-editing/default-editors
        - orodatagrid/js/row-select-for-widget/builder
        - orodatagrid/js/totals-builder
