parameters:
    akeneo_batch.logger.batch_log_handler.class:             Oro\Bundle\BatchBundle\Monolog\Handler\BatchLogHandler

services:
    oro_batch.orm.query_builder.count_query_optimizer:
        class: Oro\Bundle\BatchBundle\ORM\QueryBuilder\CountQueryBuilderOptimizer
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
            - [setRelationHelper, ['@oro_entity.helper.relation_helper']]

    oro_batch.job.repository:
        class: Oro\Bundle\BatchBundle\Job\DoctrineJobRepository
        arguments:
            - '@doctrine'
            - '%akeneo_batch.entity.job_execution.class%'
        decorates: akeneo_batch.job_repository

    oro_batch.cache.doctrine_metadata:
        public: false
        parent: oro.cache.abstract.without_memory_cache
        calls:
            - [ setNamespace, [ 'doctrine_metadata_batch' ] ]
