services:
    oro_config.api.repository:
        class: Oro\Bundle\ConfigBundle\Api\Repository\ConfigurationRepository
        arguments:
            - '@oro_config.manager.api'

    oro_config.api.handle_default_value_for_fields_filter:
        class: Oro\Bundle\ConfigBundle\Api\Processor\GetList\HandleDefaultValueForFieldsFilter
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection, priority: -25 }

    oro_config.api.set_default_value_for_fields_filter:
        class: Oro\Bundle\ConfigBundle\Api\Processor\GetList\SetDefaultValueForFieldsFilter
        arguments:
            - '@oro_api.filter_names_registry'
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection, priority: -205 }

    oro_config.api.load_configuration_sections:
        class: Oro\Bundle\ConfigBundle\Api\Processor\GetList\LoadConfigurationSections
        arguments:
            - '@oro_config.api.repository'
            - '@security.authorization_checker'
        tags:
            - { name: oro.api.processor, action: get_list, group: load_data, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }

    oro_config.api.rest.fix_configuration_sections_result_document:
        class: Oro\Bundle\ConfigBundle\Api\Processor\GetList\Rest\FixConfigurationSectionsResultDocument
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_result, requestType: rest&!json_api, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection, priority: -240 }

    oro_config.api.rest.expand_configuration_options:
        class: Oro\Bundle\ConfigBundle\Api\Processor\Get\Rest\ExpandConfigurationOptions
        tags:
            - { name: oro.api.processor, action: get, group: initialize, requestType: rest&!json_api, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }

    oro_config.api.load_configuration_section:
        class: Oro\Bundle\ConfigBundle\Api\Processor\Get\LoadConfigurationSection
        arguments:
            - '@oro_config.api.repository'
        tags:
            - { name: oro.api.processor, action: get, group: load_data, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }

    oro_config.api.rest.fix_configuration_section_result_document:
        class: Oro\Bundle\ConfigBundle\Api\Processor\Get\Rest\FixConfigurationSectionResultDocument
        tags:
            - { name: oro.api.processor, action: get, group: normalize_result, requestType: rest&!json_api, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection, priority: -240 }

    oro_config.api.add_scope_filter:
        class: Oro\Bundle\ConfigBundle\Api\Processor\AddScopeFilter
        tags:
            - { name: oro.api.processor, action: get_list, group: initialize, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }
            - { name: oro.api.processor, action: get, group: initialize, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }

    oro_config.api.get_scope:
        class: Oro\Bundle\ConfigBundle\Api\Processor\GetScope
        arguments:
            - '@oro_config.api.repository'
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }
            - { name: oro.api.processor, action: get, group: normalize_input, class: Oro\Bundle\ConfigBundle\Api\Model\ConfigurationSection }
