framework:
    assets:
        packages:
            routing:
                version: '%assets_version%'
                version_format: '%%s?dynamic_version=%%s'
                # the default format cannot be used due to the problem:
                # in case if both static and dynamic versions exist, we have duplicate of asset version parameter.
                # something like this: routes.json?version=v123&version=v123-1
                # version_format: ~ # use the default format
