placeholders:
    placeholders:
        scripts_after:
            items:
                navigationItem:
                    order: 100
        navbar:
            items:
                shortcuts:
                    order: 100
        application_menu:
            items:
                application_menu:
                    order: 100
        dots_menu:
            items:
                dots_menu:
                    order: 100

        pin_tabs_list:
            items:
                pin_tabs_list:
                    order: 100

        after_navigation: ~

        pin_button:
            items:
                pin_button:
                    order: 100
        js_modules_config:
            items:
                navigation_js_modules_config:
                    order: 100

    items:
        navigation_js_modules_config:
            template: OroNavigationBundle::js_modules_config.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
            data:
                js_routing_filename_prefix: '%oro_navigation.js_routing_filename_prefix%'
        shortcuts:
            template: OroNavigationBundle:Shortcut:shortcuts.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
        application_menu:
            template: OroNavigationBundle:ApplicationMenu:applicationMenu.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
        dots_menu:
            template: OroNavigationBundle:ApplicationMenu:dotsMenu.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
        pin_tabs_list:
            template: OroNavigationBundle:Menu:pin_tabs_list.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
        pin_button:
            template: OroNavigationBundle:ApplicationMenu:pinButton.html.twig
            applicable: '@oro_user.placeholder.filter->isUserApplicable()'
        oro_edit_menus_button:
            template: OroNavigationBundle:menuUpdate:editMenusButton.html.twig
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\UserBundle\Entity\User)'
            acl: oro_navigation_manage_menus
        oro_edit_menus_link:
            template: OroNavigationBundle:menuUpdate:editMenusLink.html.twig
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\UserBundle\Entity\User)'
            acl: oro_navigation_manage_menus
