services:
    oro_embedded_form.grid.formatter.embedded_form_type_property:
        class: Oro\Bundle\EmbeddedFormBundle\DataGrid\Formatter\EmbeddedFormTypeProperty
        arguments:
            - '@oro_embedded_form.manager'
            - '@translator'
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: embedded_form_type }
