label: Demo Theme
logo: bundles/oroui/themes/oro/images/oro-platform-logo.svg
icon: bundles/oroui/themes/oro/images/favicon.ico
styles:
    css:
        inputs:
            - bundles/oroui/themes/demo/css/scss/main.scss
        output: css/oro/oro.css
