placeholders:
    placeholders:
        scripts_before:
            items:
                filter_templates:
                    order: 5
                filter_embedded_templates:
                    order: 6
        js_modules_config:
            items:
                filter_js_modules_config:
                    order: 100

    items:
        filter_embedded_templates:
            template: OroFilterBundle:Js:embedded_templates.js.twig
        filter_js_modules_config:
            template: OroFilterBundle::js_modules_config.html.twig
            applicable: "@oro_layout.helper->isTemplateRequest()"
