services:
    oro_tag.form.tag:
        class: Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments: ["oro_tag_tag_form", Oro\Bundle\TagBundle\Form\Type\TagType]

    oro_tag.form.handler.tag:
        class: Oro\Bundle\TagBundle\Form\Handler\TagHandler
        public: true
        arguments:
            - '@oro_tag.form.tag'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    oro_tag.form.type.tag:
        class: Oro\Bundle\TagBundle\Form\Type\TagType
        tags:
            - { name: form.type, alias: oro_tag_tag }

    oro_tag.form.type.tag_select:
        class: Oro\Bundle\TagBundle\Form\Type\TagSelectType
        arguments:
            - '@security.authorization_checker'
            - '@oro_tag.form.transformer.tag_select'
            - '@oro_tag.form.subscriber.tag_select'
        tags:
            - { name: form.type, alias: oro_tag_select }

    oro_tag.form.subscriber.tag_select:
        class: Oro\Bundle\TagBundle\Form\EventSubscriber\TagSubscriber
        arguments:
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'

    oro_tag.form.transformer.tag_select:
        class: Oro\Bundle\TagBundle\Form\Transformer\TagTransformer
        arguments:  ['@oro_tag.tag.manager']

    # Entity configuration choice
    oro_tag.form.type.tag_config_choice:
        class: Oro\Bundle\TagBundle\Form\Type\TagConfigChoiceType
        arguments:
            - '@oro_entity_extend.association_type_helper'
        tags:
            - { name: form.type, alias: oro_tag_config_choice }


    # Autocomplete
    oro_tag.autocomplete.tag.search_handler:
        class: Oro\Bundle\TagBundle\Autocomplete\SearchHandler
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Oro\Bundle\TagBundle\Entity\Tag'
            - ["name"]
            - '@oro_security.token_accessor'
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: tags, acl_resource: oro_tag_assign_unassign }

    # API
    oro_tag.form.type.tag.api:
        class: Oro\Bundle\TagBundle\Form\Type\TagApiType
        tags:
            - { name: form.type, alias: oro_tag_tag }

    oro_tag.form.tag.api:
        class: Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments: ["oro_tag_tag_form", Oro\Bundle\TagBundle\Form\Type\TagType, null]

    oro_tag.form.handler.api:
        class: Oro\Bundle\TagBundle\Form\Handler\TagHandler
        public: true
        arguments:
            - '@oro_tag.form.type.tag.api'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    oro_tag.form.handler.taggable.api:
        class: Oro\Bundle\TagBundle\Form\Handler\TagEntityApiHandler
        public: true
        arguments:
            - '@oro_tag.form.taggable.api'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'

    oro_tag.form.type.taggable.api:
        class: Oro\Bundle\TagBundle\Form\Type\TagEntityApiType
        tags:
            - { name: form.type, alias: oro_tag_tag_api }

    oro_tag.form.tag_collection.api:
        class: Oro\Bundle\TagBundle\Form\Type\TagCollectionApiType
        tags:
            - { name: form.type, alias: oro_tag_collection_api }

    oro_tag.form.tag_standalone_collection.api:
        class: Oro\Bundle\TagBundle\Form\Type\TagStandaloneCollectionApiType
        tags:
            - { name: form.type, alias: oro_tag_standalone_collection_api }

    oro_tag.form.taggable.api:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - tags
            - Oro\Bundle\TagBundle\Form\Type\TagStandaloneCollectionApiType

    oro_tag.form.taxonomy:
        class: Symfony\Component\Form\Form
        public: true
        factory: ['@form.factory', createNamed]
        arguments: ["oro_tag_taxonomy_form", Oro\Bundle\TagBundle\Form\Type\TaxonomyType]

    oro_tag.form.handler.taxonomy:
        class: Oro\Bundle\TagBundle\Form\Handler\TaxonomyHandler
        public: true
        arguments:
            - '@oro_tag.form.taxonomy'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    oro_tag.form.type.taxonomy:
        class: Oro\Bundle\TagBundle\Form\Type\TaxonomyType
        tags:
            - { name: form.type, alias: oro_tag_taxonomy }

    oro_tag.form.type.taxonomy_select:
       class: Oro\Bundle\TagBundle\Form\Type\TaxonomySelectType
       tags:
           - { name: form.type, alias: oro_taxonomy_select }

    oro_tag.form.type.filter.tags_report:
        class: Oro\Bundle\TagBundle\Form\Type\Filter\TagsReportFilterType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_type_tags_report_filter }
