services:
    oro_tag.tag.manager:
        class: Oro\Bundle\TagBundle\Entity\TagManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Oro\Bundle\TagBundle\Entity\Tag'
            - 'Oro\Bundle\TagBundle\Entity\Tagging'
            - '@security.authorization_checker'
            - '@oro_security.token_accessor'
            - '@router'

    oro_tag.docrine.event.listener:
        class: Oro\Bundle\TagBundle\EventListener\TagListener
        arguments:
            - '@oro_tag.helper.taggable_helper'
        calls:
            - [setContainer,  ['@service_container']]
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    oro_tag.provider.search_provider:
        class: Oro\Bundle\TagBundle\Provider\SearchProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_search.mapper'
            - '@oro_tag.security_provider'
            - '@oro_search.index'
            - '@oro_entity_config.config_manager'
            - '@translator'

    # Tag API
    oro_tag.tag.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\TagBundle\Entity\Tag'
            - '@doctrine.orm.entity_manager'

    oro_tag.taxonomy.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\TagBundle\Entity\Taxonomy'
            - '@doctrine.orm.entity_manager'

    oro_tag.twig.tag.extension:
        class: Oro\Bundle\TagBundle\Twig\TagExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_tag.security_provider:
        class: Oro\Bundle\TagBundle\Security\SecurityProvider
        arguments:
            - '@oro_search.security_provider'

    oro_tag.event_listener.search_results_grid_listener:
        class: Oro\Bundle\TagBundle\EventListener\TagSearchResultsGridListener
        arguments:
          - '@oro_tag.security_provider'
          - '@oro_entity.entity_alias_resolver'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.tag-results-grid, method: onBuildAfter }

    oro_tag.owner_assignment_checker.tag:
        class: Oro\Bundle\TagBundle\Ownership\TagOwnerAssignmentChecker
        tags:
            - { name: oro_organization.owner_assignment_checker, entity: Oro\Bundle\TagBundle\Entity\Tag }

    # Merge listener
    oro_tag.event_listener.merge_listener:
        class: Oro\Bundle\TagBundle\EventListener\MergeListener
        arguments:
          - '@oro_tag.tag.manager'
          - '@oro_tag.helper.taggable_helper'
        tags:
          - { name: kernel.event_listener, event: oro.entity_merge.build_metadata, method: onBuildMetadata }
          - { name: kernel.event_listener, event: oro.entity_merge.create_entity_data, method: onCreateEntityData }
          - { name: kernel.event_listener, event: oro.entity_merge.after_merge_entity, method: afterMergeEntity }

    oro_tag.provider.virtual_relation.tags:
        class: Oro\Bundle\TagBundle\Provider\TagVirtualRelationProvider
        public: false
        arguments:
            - '@oro_tag.helper.taggable_helper'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_entity.virtual_relation_provider, priority: 150 }

    oro_tag.virtual_field_provider:
        class: Oro\Bundle\TagBundle\Provider\TagVirtualFieldProvider
        public: false
        arguments:
            - '@oro_tag.helper.taggable_helper'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_entity.virtual_field_provider, priority: 150 }

    oro_tag.filter.tags_choice_tree:
        class: Oro\Bundle\TagBundle\Filter\TagsDictionaryFilter
        public: false
        parent: 'oro_filter.dictionary_filter'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: tag }

    oro_tag.filter.tags_report:
        class: Oro\Bundle\TagBundle\Filter\TagsReportFilter
        public: false
        parent: 'oro_filter.dictionary_filter'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: tags-report }

    oro_tag.grid.tags_extension:
        class: Oro\Bundle\TagBundle\Grid\TagsExtension
        arguments:
            - '@oro_tag.tag.manager'
            - '@oro_entity.orm.entity_class_resolver'
            - '@oro_tag.helper.taggable_helper'
            - '@oro_entity.routing_helper'
            - '@security.authorization_checker'
            - '@security.token_storage'
        calls:
            - [addUnsupportedGridPrefix, ['oro_report']]
            - [addUnsupportedGridPrefix, ['oro_segment']]
        tags:
            - { name: oro_datagrid.extension }

    oro_tag.grid.tags_report_extension:
        class: Oro\Bundle\TagBundle\Grid\TagsReportExtension
        arguments:
            - '@oro_tag.tag.manager'
            - '@oro_entity.orm.entity_class_resolver'
            - '@oro_tag.helper.taggable_helper'
            - '@oro_entity.routing_helper'
        calls:
            - [addUnsupportedGridPrefix, ['oro_report']]
            - [addUnsupportedGridPrefix, ['oro_segment']]
        tags:
            - { name: oro_datagrid.extension }

    oro_tag.extension.grid.formatter.tag_search_result_property:
        class: Oro\Bundle\TagBundle\Grid\Formatter\TagSearchResultProperty
        arguments:
            - '@twig'
            - '@oro_entity_config.provider.entity'
            - OroTagBundle:Search:searchResultItem.html.twig
        calls:
            - [setMappingProvider,  ['@oro_search.provider.search_mapping']]
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: tag-search-result }

    oro_tag.provider.statistic:
        class: Oro\Bundle\TagBundle\Provider\StatisticProvider
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_tag.security_provider'
            - '@oro_entity_config.provider.entity'
            - '@oro_entity.entity_alias_resolver'

    oro_tag.taxonomy.provider.statistic:
        class: Oro\Bundle\TagBundle\Provider\TaxonomyStatisticProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_tag.security_provider'
            - '@oro_entity_config.provider.entity'
            - '@oro_entity.entity_alias_resolver'

    oro_tag.extension.tag_search_results:
        class: Oro\Bundle\TagBundle\Grid\Extension\TagSearchResultsExtension
        arguments:
            - '@oro_search.formatter.result_formatter'
            - '@oro_search.mapper'
            - '@event_dispatcher'
        tags:
            - { name: oro_datagrid.extension }

    oro_tag.view.eventlistener.tag_field:
        class: Oro\Bundle\TagBundle\EventListener\TagFieldListener
        arguments:
            - '@oro_tag.helper.taggable_helper'
        tags:
            - { name: kernel.event_listener, event: entity_view.render.before, method: addTagField }

    oro_tag.model.accessor.tag_merge:
        class: Oro\Bundle\TagBundle\Model\Accessor\TagMergeAccessor
        arguments:
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'
        tags:
            - { name: oro_entity_merge.accessor }

    oro_tag.helper.taggable_helper:
        class: Oro\Bundle\TagBundle\Helper\TaggableHelper
        arguments:
            - '@oro_entity_config.provider.tag'

    oro_tag.eventlistener.entity_config:
        class: Oro\Bundle\TagBundle\EventListener\EntityConfigListener
        arguments:
            - '@oro_tag.tag.manager'
        tags:
            - { name: kernel.event_listener, event: oro.entity_config.post_flush, method: postFlush }

    oro_tag.formatter.tags_formatter:
        class: Oro\Bundle\TagBundle\Formatter\TagsTypeFormatter
        public: true
        tags:
            - { name: oro_importexport.formatter.formatter, data_type: tags, format_type: excel }

    oro_tag.workflow.action.copy_tagging:
        class: Oro\Bundle\TagBundle\Workflow\Action\CopyTagging
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'
        tags:
            - { name: oro_action.action, alias: copy_tagging }

    oro_tag.workflow.action.add_tagging_to_new_entity:
        class: 'Oro\Bundle\TagBundle\Workflow\Action\CopyTaggingToNewEntity'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_action.action, alias: copy_tagging_to_new_entity }
            - { name: oro_workflow.action, alias: copy_tagging_to_new_entity }

    oro_tag.event_listener.import_export_tags_subscriber:
        class: Oro\Bundle\TagBundle\EventListener\ImportExportTagsSubscriber
        arguments:
            - '@oro_tag.link.tag_import.manager'
        tags:
            - { name: kernel.event_subscriber }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }

    oro_tag.link.tag_import.manager:
        tags:
            - { name: oro_service_link, service: oro_tag.tag_import.manager }

    oro_tag.tag_import.manager:
        class: Oro\Bundle\TagBundle\Manager\TagImportManager
        arguments:
            - '@oro_tag.tag.manager'
            - '@oro_tag.helper.taggable_helper'

    oro_tag.form.autocomplete.taxonomy.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Oro\Bundle\TagBundle\Entity\Taxonomy'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: taxonomy, acl_resource: oro_taxonomy_view }
