aliases:
    oro/datagrid/action/button-widget-action$: oroaction/js/datagrid/action/button-widget-action
dynamic-imports:
    oroaction:
        - oroaction/js/app/components/button-component
    orodatagrid:
        - oro/datagrid/action/button-widget-action
