parameters:
    translator.class:                                           Oro\Bundle\TranslationBundle\Translation\Translator

services:
    oro_translation.controller:
        class: Oro\Bundle\TranslationBundle\Controller\Controller
        public: true
        arguments:
            - '@translator.default'
            - '@templating'
            - OroTranslationBundle:Translation:translation.js.twig
            - ""
        lazy: true

    oro_translation.extractor.php_code_extractor:
        class: Oro\Bundle\TranslationBundle\Extractor\PhpCodeExtractor
        arguments:
            - '@service_container'
        tags:
            - { name: translation.extractor, alias: oro_translation_php_extractor }

    oro_translation.service_provider:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationServiceProvider
        arguments:
            - '@oro_translation.uploader.default_adapter'
            - '@oro_translation.js_dumper'
            - '@translation.reader'
            - '@oro_translation.database_translation.persister'
            - '%kernel.cache_dir%'
        lazy: true

    oro_translation.statistic_provider:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationStatisticProvider
        arguments:
            - '@oro_translation.cache'
            - '@oro_translation.oro_translation_adapter'
            - '@oro_translation.packages_provider'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: oro_translation }

    # guzzle http client for crowdin
    oro_translation.guzzle_crowdin_client:
        class: Guzzle\Http\Client
        arguments:
            - '%oro_translation.api.crowdin.endpoint%'
        lazy: true

    # guzzle http client for oro proxy
    oro_translation.guzzle_oro_client:
        class: Guzzle\Http\Client
        arguments:
            - '%oro_translation.api.oro_service.endpoint%'
        lazy: true

    oro_translation.uploader.crowdin_adapter:
        class: Oro\Bundle\TranslationBundle\Provider\CrowdinAdapter
        arguments:
            - '@oro_translation.guzzle_crowdin_client'
        tags:
            - { name: translation_adapter, alias: crowdin }

    oro_translation.oro_translation_adapter:
        class: Oro\Bundle\TranslationBundle\Provider\OroTranslationAdapter
        arguments:
            - '@oro_translation.guzzle_oro_client'
        calls:
            - [ setApiKey, [ '%oro_translation.api.oro_service.key%' ] ]
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: oro_translation }

    oro_translation.database_translation.metadata.cache:
        class: Oro\Bundle\TranslationBundle\Translation\DynamicTranslationMetadataCache
        arguments:
            - '@oro_translation.database_translation.metadata.cache_impl'

    oro_translation.database_translation.metadata.cache_impl:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_db_trans_metadata' ] ]

    oro_translation.database_translation.persister:
        class: Oro\Bundle\TranslationBundle\Translation\DatabasePersister
        arguments:
            - '@doctrine'
            - '@oro_translation.manager.translation'

    oro_translation.database_translation.loader:
        class: Oro\Bundle\TranslationBundle\Translation\OrmTranslationLoader
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.database_checker'
        tags:
            - { name: translation.loader, alias: oro_database_translation }

    oro_translation.database_checker:
        public: false
        class: Oro\Bundle\EntityBundle\Tools\DatabaseChecker
        arguments:
            - '@doctrine'
            - ['oro_translation']
            - '%installed%'
        tags:
            - { name: oro_entity.database_checker }

    oro_translation.empty_array.loader:
        class: Oro\Bundle\TranslationBundle\Translation\EmptyArrayLoader

    oro_translation.selector:
        class: Oro\Bundle\TranslationBundle\Translation\MessageSelector
        decorates: translator.selector
        arguments:
            - '@logger'

    oro_translation.cache:
        parent: oro.cache.abstract
        calls:
            - [setNamespace, [ 'oro_trans' ] ]

    oro_translation.resource.cache:
        public: false
        class: Doctrine\Common\Cache\ArrayCache

    oro_translation.cache.translation_cache_warmer:
        class: Oro\Bundle\TranslationBundle\Cache\TranslationCacheWarmer
        public: false
        decorates: 'translation.warmer'
        decoration_inner_name: 'translation.warmer.default'
        arguments:
            - '@translation.warmer.default'
            - '@oro_translation.strategy.provider'

    oro_translation.js_dumper:
        class: Oro\Bundle\TranslationBundle\Provider\JsTranslationDumper
        arguments:
            - '@oro_translation.controller'
            - '@router'
            - '%oro_translation.js_translation.domains%'
            - '%kernel.project_dir%'
            - '@oro_translation.provider.language'
        lazy: true
        public: true

    oro_translation.twig.translation.extension:
        class: Oro\Bundle\TranslationBundle\Twig\TranslationExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
            - '%oro_translation.debug_translator%'
            - '%oro_translation.js_translation.debug%'
        tags:
            - { name: twig.extension }

    oro_translation.packages_provider:
        class: Oro\Bundle\TranslationBundle\Provider\PackagesProvider
        arguments:
            - '%kernel.bundles%'
            - '%kernel.project_dir%'
            - ['@oro_translation.packages_provider.translation']

    oro_translation.packages_provider.translation:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationPackageProvider
        arguments:
            - !tagged_iterator oro_translation.extension.packages_provider

    # this instance of the composer does not require the full initialization
    # and can work without Phar and Zip PHP extensions
    oro_translation.composer:
        class: Composer\Composer
        public: false
        factory: ['@oro_translation.composer.factory', createComposer]
        arguments:
            - '@oro_translation.composer.io'
            - '%kernel.project_dir%/composer.json'
            - false
            - ~
            - false
        lazy: true

    oro_translation.composer.factory:
        class: Composer\Factory
        public: false

    oro_translation.composer.io:
        class: Composer\IO\BufferIO
        public: false

    oro_translation.extension.transtation_packages_provider.abstract:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationPackagesProviderExtension
        abstract: true
        public: false
        arguments:
            - '@oro_platform.composer.local_repo_factory'
            - '@oro_translation.composer'

    oro_translation.extension.transtation_packages_provider:
        parent: oro_translation.extension.transtation_packages_provider.abstract
        calls:
            - ['addPackage', ['Oro', 'oro/platform', '/src']]
            - ['addPackage', ['Oro', 'oro/calendar-bundle']]
            - ['addPackage', ['Oro', 'oro/platform-serialised-fields']]
        tags:
            - {name: oro_translation.extension.packages_provider}

    oro_translation.query_hint.translatable:
        public: false
        abstract: true
        tags:
            -
                name: oro_entity.query_hint
                hint: oro_translation.translatable
                alias: HINT_TRANSLATABLE
                output_walker: Oro\Component\DoctrineUtils\ORM\Walker\TranslatableSqlWalker

    oro_translation.event_listener.translation:
        class: Oro\Bundle\TranslationBundle\EventListener\TranslationListener
        lazy: true
        arguments:
            - '@oro_translation.database_translation.metadata.cache'
            - 'import.language_translations_import_from_csv'
        tags:
            - {name: kernel.event_listener, event: oro.import_export.after_job_execution, method: onAfterImportTranslations}

    oro_translation.strategy.default:
        class: Oro\Bundle\TranslationBundle\Strategy\DefaultTranslationStrategy
        public: false
        arguments:
            - '@oro_translation.provider.language'
            - '%installed%'
        tags:
            - { name: oro_translation.extension.translation_strategy }

    oro_translation.strategy.provider:
        class: Oro\Bundle\TranslationBundle\Strategy\TranslationStrategyProvider
        arguments:
            - !tagged_iterator oro_translation.extension.translation_strategy

    oro_translation.listener.datagrid.language:
        class: Oro\Bundle\TranslationBundle\EventListener\Datagrid\LanguageListener
        arguments:
            - '@oro_translation.helper.language'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.oro-translation-language-grid, method: onResultAfter }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.oro-translation-language-grid, method: onBuildBefore }

    oro_translation.listener.datagrid.translation:
        class: Oro\Bundle\TranslationBundle\EventListener\Datagrid\TranslationListener
        arguments:
            - '@oro_translation.provider.language'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.oro-translation-translations-grid, method: onBuildBefore }

    oro_translation.listener.datagrid.translatable:
        class: Oro\Bundle\TranslationBundle\EventListener\Datagrid\TranslatableListener
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.before, method: onResultBefore }

    oro_translation.repository.language:
        class: Oro\Bundle\TranslationBundle\Entity\Repository\LanguageRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\TranslationBundle\Entity\Language'

    oro_translation.provider.translation_context:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationContextProvider
        public: true
        arguments:
            - !tagged_iterator oro_translation.extension.translation_context_resolver

    oro_translation.extension.translation_context_resolver:
        class: Oro\Bundle\TranslationBundle\Extension\TranslationContextResolver
        arguments:
            - '@translator'
        tags:
            - { name: oro_translation.extension.translation_context_resolver, priority: -100 }

    oro_translation.provider.language:
        class: Oro\Bundle\TranslationBundle\Provider\LanguageProvider
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'
            - '@oro_security.acl_helper'

    oro_translation.helper.language:
        class: Oro\Bundle\TranslationBundle\Helper\LanguageHelper
        public: true
        arguments:
            - '@oro_translation.statistic_provider'
            - '@oro_translation.packages_provider'
            - '@oro_translation.oro_translation_adapter'
            - '@oro_translation.service_provider'
            - '@oro_config.global'

    oro_translation.manager.translation:
        class: Oro\Bundle\TranslationBundle\Manager\TranslationManager
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.provider.translation_domain'
            - '@oro_translation.database_translation.metadata.cache'
            - '@event_dispatcher'

    oro_translation.cache.provider.domains:
        parent: oro.cache.abstract
        public: false
        calls:
            - [ setNamespace, [ 'oro_translation_domains' ] ]

    oro_translation.provider.translation_domain:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationDomainProvider
        public: true
        arguments:
            - '@doctrine'
            - '@oro_translation.cache.provider.domains'

    oro_translation.helper.translation:
        class: Oro\Bundle\TranslationBundle\Helper\TranslationHelper
        arguments:
            - '@doctrine'

    oro_translation.filter.language:
        class: Oro\Bundle\TranslationBundle\Filter\LanguageFilter
        public: false
        parent: oro_filter.entity_filter
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: language }

    oro_translation.helper.translation_route:
        class: Oro\Bundle\TranslationBundle\Helper\TranslationsDatagridRouteHelper
        arguments:
            - '@oro_datagrid.helper.route'

    oro_translation.layout.data_provider.translator:
        class: Oro\Bundle\TranslationBundle\Layout\DataProvider\TranslatorProvider
        arguments:
            - '@translator'
        tags:
            - { name: layout.data_provider, alias: translator }

    oro_translation.mass_action.reset_translation:
        class: Oro\Bundle\TranslationBundle\Datagrid\Extension\MassAction\ResetTranslationsMassAction
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: reset_translations }

    oro_translation.mass_action.reset_translation_handler:
        class: Oro\Bundle\TranslationBundle\Datagrid\Extension\MassAction\ResetTranslationsMassActionHandler
        public: true
        arguments:
           - '@oro_translation.manager.translation'
           - '@translator'
           - '@oro_security.acl_helper'

    oro_translation.provider.external_translations:
        class: Oro\Bundle\TranslationBundle\Provider\ExternalTranslationsProvider
        public: true
        arguments:
           - '@oro_translation.service_provider'
           - '@oro_translation.helper.language'
           - '@oro_entity.doctrine_helper'

    oro_translation.migration.demo_data_fixtures_listener.js_translation_dump:
        class: Oro\Bundle\TranslationBundle\EventListener\JsTranslationDumpDemoDataListener
        arguments:
            - '@oro_translation.js_dumper'
            - '@oro_translation.provider.language'
            - '%installed%'
        tags:
            - { name: kernel.event_listener, event: oro_migration.data_fixtures.post_load, method: onPostLoad, priority: -100 }

    oro_translation.translation_pack_dumper:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationPackDumper
        arguments:
            - '@translation.writer'
            - '@translation.extractor'
            - '@translation.reader'
            - '@filesystem'
            - '@oro_translation.packages_provider.translation'
            - "@=service('kernel').getBundles()"

    oro_translation.translation_adapters_collection:
        class: Oro\Bundle\TranslationBundle\Provider\TranslationAdaptersCollection
        arguments:
            - ~ # adapters

    oro_translation.async.message_processor.dump_js_translations:
        class: Oro\Bundle\TranslationBundle\Async\DumpJsTranslationsMessageProcessor
        arguments:
            - '@oro_translation.js_dumper'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
