services:
    oro_importexport.data_converter.default:
        class: Oro\Bundle\ImportExportBundle\Converter\DefaultDataConverter

    oro_importexport.data_converter.configurable:
        class: Oro\Bundle\ImportExportBundle\Converter\ConfigurableTableDataConverter
        abstract: true
        arguments:
            - '@oro_entity.helper.field_helper'
            - '@oro_importexport.data_converter.relation_calculator'
            - '@oro_locale.settings'
        calls:
            - [setDispatcher, ['@event_dispatcher']]
            - [setConfigManager, ['@oro_config.manager']]

    oro_importexport.data_converter.template_fixture.configurable:
        class: Oro\Bundle\ImportExportBundle\Converter\ConfigurableTableDataConverter
        abstract: true
        arguments:
            - '@oro_entity.helper.field_helper'
            - '@oro_importexport.data_converter.template_fixture.relation_calculator'
            - '@oro_locale.settings'
        calls:
            - [setDispatcher, ['@event_dispatcher']]

    oro_importexport.data_converter.relation_calculator:
        class: Oro\Bundle\ImportExportBundle\Converter\RelationCalculator
        arguments:
            - '@doctrine'
            - '@oro_entity.helper.field_helper'

    oro_importexport.data_converter.template_fixture.relation_calculator:
        class: Oro\Bundle\ImportExportBundle\Converter\TemplateFixtureRelationCalculator
        arguments:
            - '@oro_importexport.template_fixture.manager'
            - '@oro_entity.helper.field_helper'
