services:
    oro_importexport.field.field_helper.link:
        tags:
            - { name: oro_service_link, service: oro_entity.helper.field_helper }

    oro_importexport.field.related_entity_state_helper:
        class: Oro\Bundle\ImportExportBundle\Field\RelatedEntityStateHelper
        arguments:
            - '@oro_entity.helper.field_helper'
            - '@oro_entity.doctrine_helper'

    oro_importexport.field.database_helper:
        class: Oro\Bundle\ImportExportBundle\Field\DatabaseHelper
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_importexport.field.field_helper.link'
            - '@oro_security.token_accessor'
            - '@oro_security.owner.ownership_metadata_provider.link'
        tags:
            - { name: doctrine.event_listener, event: onClear }
