services:
    oro_importexport.form.type.import:
        class: Oro\Bundle\ImportExportBundle\Form\Type\ImportType
        arguments:
            - '@oro_importexport.processor.registry'
        tags:
            - { name: form.type, alias: oro_importexport_import }

    oro_importexport.form.type.export:
        class: Oro\Bundle\ImportExportBundle\Form\Type\ExportType
        arguments:
            - '@oro_importexport.processor.registry'
        tags:
            - { name: form.type, alias: oro_importexport_export }

    oro_importexport.form.type.export_template:
        class: Oro\Bundle\ImportExportBundle\Form\Type\ExportTemplateType
        arguments:
            - '@oro_importexport.processor.registry'
        tags:
            - { name: form.type, alias: oro_importexport_export_template }

    oro_importexport.form.type.identity_config_choice:
        class: Oro\Bundle\ImportExportBundle\Form\Type\IdentityConfigChoiceType
        arguments:
            - '@oro_entity_extend.association_type_helper'
            - '@doctrine'
        tags:
            - { name: form.type, alias: oro_importexport_identity_config_choice }
