services:
    oro_importexport.handler.abstract:
        class: Oro\Bundle\ImportExportBundle\Handler\AbstractHandler
        abstract: true
        arguments:
            - '@oro_importexport.job_executor'
            - '@oro_importexport.processor.registry'
            - '@oro_entity_config.provider.entity'
            - '@translator'
            - '@oro_importexport.writer.writer_chain'
            - '@oro_importexport.reader.reader_chain'
            - ~
            - '@oro_importexport.file.file_manager'

    oro_importexport.handler.import:
        class: Oro\Bundle\ImportExportBundle\Handler\ImportHandler
        parent: oro_importexport.handler.abstract
        arguments:
            index_6: '@oro_importexport.file.batch_file_manager.import'
        lazy: true

    oro_importexport.handler.export:
        class: Oro\Bundle\ImportExportBundle\Handler\ExportHandler
        parent: oro_importexport.handler.abstract
        arguments:
            index_6: '@oro_importexport.file.batch_file_manager.export'
        lazy: true

    Oro\Bundle\ImportExportBundle\Handler\ExportHandler:
        alias: 'oro_importexport.handler.export'

    oro_importexport.handler.csv.file:
        class: Oro\Bundle\ImportExportBundle\Handler\CsvFileHandler

    Oro\Bundle\ImportExportBundle\Handler\CsvFileHandler:
        alias: 'oro_importexport.handler.csv.file'

    oro_importexport.handler.postpone:
        class: Oro\Bundle\ImportExportBundle\Handler\PostponedRowsHandler
        public: false
        arguments:
            - '@oro_importexport.file.file_manager'
            - '@oro_message_queue.client.message_producer'
            - '@oro_importexport.writer.writer_chain'
            - '@translator'
