services:
    # Processor registry
    oro_importexport.processor.registry:
        class: Oro\Bundle\ImportExportBundle\Processor\ProcessorRegistry
        public: true

    # Import delegate processor, abstract import processor
    oro_importexport.processor.import_delegate:
        class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor
        arguments:
            - '@oro_importexport.processor.registry'
            - "import"
            - '@oro_importexport.context_registry'

    oro_importexport.processor.import_abstract:
        class: Oro\Bundle\ImportExportBundle\Processor\ImportProcessor
        abstract: true
        calls:
            - [setSerializer, ['@oro_importexport.serializer']]

    # Export delegate processor, abstract import processor
    oro_importexport.processor.export_delegate:
        class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor
        arguments:
            - '@oro_importexport.processor.registry'
            - "export"
            - '@oro_importexport.context_registry'

    oro_importexport.processor.export_template_delegate:
        class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor
        arguments:
            - '@oro_importexport.processor.registry'
            - "export_template"
            - '@oro_importexport.context_registry'

    oro_importexport.processor.export_abstract:
        class: Oro\Bundle\ImportExportBundle\Processor\ExportProcessor
        abstract: true
        calls:
            - [setSerializer, ['@oro_importexport.serializer']]

    # Import validate processor
    oro_importexport.processor.import_validation_delegate:
        class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor
        arguments:
            - '@oro_importexport.processor.registry'
            - "import_validation"
            - '@oro_importexport.context_registry'
