parameters:
    oro_importexport.template_fixture.entity_registry.class:  Oro\Bundle\ImportExportBundle\TemplateFixture\TemplateEntityRegistry
    oro_importexport.template_fixture.manager.class:          Oro\Bundle\ImportExportBundle\TemplateFixture\TemplateManager
    oro_importexport.action.execute_job.class:                Oro\Bundle\ImportExportBundle\Model\Action\ExecuteJobAction
    oro_importexport.import.size_of_batch: 100
    oro_importexport.export.size_of_batch: 5000
    oro_importexport.importexport_dir: import_export

services:
    oro_importexport.template_fixture.entity_registry:
        class: '%oro_importexport.template_fixture.entity_registry.class%'
        calls:
            - [setDispatcher, ['@event_dispatcher']]

    oro_importexport.template_fixture.manager:
        class: '%oro_importexport.template_fixture.manager.class%'
        arguments:
            - '@oro_importexport.template_fixture.entity_registry'

    oro_importexport.action.execute_job:
        class: '%oro_importexport.action.execute_job.class%'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_importexport.job_executor'
        tags:
            - { name: oro_action.action, alias: execute_job }

    oro_importexport.formatter.formatter_provider:
        class: 'Oro\Bundle\ImportExportBundle\Formatter\FormatterProvider'
        arguments:
            - '@service_container'
            - []
            - []
        public: false

    oro_importexport.formatter.excel_datetime:
        class: 'Oro\Bundle\ImportExportBundle\Formatter\ExcelDateTimeTypeFormatter'
        arguments:
            - '@oro_locale.settings'
            - '@translator'
        tags:
            - { name: oro_importexport.formatter.formatter, data_type: datetime, format_type: excel}
            - { name: oro_importexport.formatter.formatter, data_type: date, format_type: excel}
            - { name: oro_importexport.formatter.formatter, data_type: time, format_type: excel}

    oro_importexport.formatter.locale_number:
        class: 'Oro\Bundle\ImportExportBundle\Formatter\NumberTypeFormatter'
        arguments:
            - '@oro_locale.formatter.number'
        tags:
            - { name: oro_importexport.formatter.formatter, data_type: currency, format_type: excel }
            - { name: oro_importexport.formatter.formatter, data_type: percent, format_type: excel }
            - { name: oro_importexport.formatter.formatter, data_type: integer, format_type: excel }
            - { name: oro_importexport.formatter.formatter, data_type: decimal, format_type: excel }

    oro_importexport.async.import_export_result_summarizer:
        class: 'Oro\Bundle\ImportExportBundle\Async\ImportExportResultSummarizer'
        arguments:
            - '@router'
            - '@oro_config.global'
            - '@oro_importexport.file.file_manager'
        public: false

    oro_importexport.writer.writer_chain:
        class: 'Oro\Bundle\ImportExportBundle\Writer\WriterChain'

    oro_importexport.reader.reader_chain:
        class: 'Oro\Bundle\ImportExportBundle\Reader\ReaderChain'

    oro_importexport.file.file_manager:
        class: 'Oro\Bundle\ImportExportBundle\File\FileManager'
        arguments:
          - '@knp_gaufrette.filesystem_map'

    oro_importexport.file.batch_file_manager.abstract:
        class: 'Oro\Bundle\ImportExportBundle\File\BatchFileManager'
        abstract: true
        arguments:
          - '@oro_importexport.file.file_manager'

    oro_importexport.file.batch_file_manager.import:
        parent: oro_importexport.file.batch_file_manager.abstract
        public: false
        arguments:
          - '%oro_importexport.import.size_of_batch%'

    oro_importexport.file.batch_file_manager.export:
        parent: oro_importexport.file.batch_file_manager.abstract
        public: false
        arguments:
          - '%oro_importexport.export.size_of_batch%'

    oro_importexport.job.context.aggregator_registry:
        class: 'Oro\Bundle\ImportExportBundle\Job\Context\ContextAggregatorRegistry'
        public: false

    oro_importexport.job.context.aggregator.selective:
        class: 'Oro\Bundle\ImportExportBundle\Job\Context\SelectiveContextAggregator'
        public: false
        arguments:
            - '@oro_importexport.context_registry'
        tags:
            - { name: 'oro_importexport.job.context.aggregator' }

    oro_importexport.job.context.aggregator.simple:
        class: 'Oro\Bundle\ImportExportBundle\Job\Context\SimpleContextAggregator'
        public: false
        arguments:
            - '@oro_importexport.context_registry'
        tags:
            - { name: 'oro_importexport.job.context.aggregator' }

    oro_importexport.configuration.registry:
        class: 'Oro\Bundle\ImportExportBundle\Configuration\ImportExportConfigurationRegistry'

    oro_importexport.twig_extension.get_import_export_configuration:
        class: 'Oro\Bundle\ImportExportBundle\Twig\GetImportExportConfigurationExtension'
        arguments:
            - '@oro_importexport.configuration.registry'
        tags:
            - { name: 'twig.extension' }

    oro_importexport.twig_extension.basename:
        class: 'Oro\Bundle\ImportExportBundle\Twig\BasenameTwigExtension'
        public: false
        tags:
            - { name: twig.extension }

    oro_importexport.validator.identity_validation_loader:
        class: Oro\Bundle\ImportExportBundle\Validator\IdentityValidationLoader
        public: false
        arguments:
            - '@oro_entity_config.provider.extend'
            - '@oro_entity_config.provider.importexport'
            - '@oro_entity.doctrine_helper'
        calls:
            -
                - addConstraints
                -
                    - integer
                    -
                        - Regex:
                              pattern: '/^[+-]?\d+$/'
                              message: "This value should contain only valid integer."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - smallint
                    -
                        - Regex:
                              pattern: '/^[+-]?\d+$/'
                              message: "This value should contain only valid integer."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - bigint
                    -
                        - Regex:
                              pattern: '/^[+-]?\d+$/'
                              message: "This value should contain only valid integer."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - float
                    -
                        - Regex:
                              pattern: '/^[+-]?((\d+\.?\d*)|(\.\d+))*$/'
                              message: "This value should contain only valid float."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - decimal
                    -
                        - Regex:
                              pattern: '/^[+-]?((\d+\.?\d*)|(\.\d+))*$/'
                              message: "This value should contain only valid decimal."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - money
                    -
                        - Regex:
                              pattern: '/^[+-]?((\d+\.?\d*)|(\.\d+))*$/'
                              message: "This value should contain only valid decimal."
                              groups: ['import_identity']
            -
                - addConstraints
                -
                    - percent
                    -
                        - Regex:
                              pattern: '/^[+-]?((\d+\.?\d*)|(\.\d+))*$/'
                              message: "This value should contain only valid float."
                              groups: ['import_identity']
