services:
    oro_importexport.strategy.import.helper:
        class: Oro\Bundle\ImportExportBundle\Strategy\Import\ImportStrategyHelper
        arguments:
            - '@doctrine'
            - '@validator'
            - '@translator'
            - '@oro_entity.helper.field_helper'
            - '@oro_user.importexport.data_converter'
            - '@security.authorization_checker'
            - '@oro_security.token_accessor'
            - '@oro_security.owner.checker'
        calls:
            - [setConfigProvider, ['@oro_entity_config.provider.extend']]

    oro_importexport.strategy.add:
        abstract: true
        arguments:
            - '@event_dispatcher'
            - '@oro_importexport.strategy.import.helper'
            - '@oro_entity.helper.field_helper'
            - '@oro_importexport.field.database_helper'

    oro_importexport.strategy.abstract_import_strategy:
        class: Oro\Bundle\ImportExportBundle\Strategy\Import\AbstractImportStrategy
        abstract: true
        arguments:
            - '@event_dispatcher'
            - '@oro_importexport.strategy.import.helper'
            - '@oro_entity.helper.field_helper'
            - '@oro_importexport.field.database_helper'

    oro_importexport.strategy.configurable_add_or_replace:
        class: Oro\Bundle\ImportExportBundle\Strategy\Import\ConfigurableAddOrReplaceStrategy
        abstract: true
        arguments:
            - '@event_dispatcher'
            - '@oro_importexport.strategy.import.helper'
            - '@oro_entity.helper.field_helper'
            - '@oro_importexport.field.database_helper'
            - '@oro_entity.entity_class_name_provider'
            - '@translator'
            - '@oro_importexport.strategy.new_entities_helper'
            - '@oro_entity.doctrine_helper'
            - '@oro_importexport.field.related_entity_state_helper'

    oro_importexport.strategy.new_entities_helper:
        class: Oro\Bundle\ImportExportBundle\Strategy\Import\NewEntitiesHelper
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: onClear }
