services:
    oro_query_designer.form.type.field_choice:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\FieldChoiceType
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: oro_field_choice }

    oro_query_designer.form.type.date_field_choice:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\DateFieldChoiceType
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: oro_date_field_choice }

    oro_query_designer.form.type.function_choice:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\FunctionChoiceType
        arguments:
            - '@oro_query_designer.query_designer.manager'
        tags:
            - { name: form.type, alias: oro_function_choice }

    oro_query_designer.form.type.sorting_choice:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\SortingChoiceType
        tags:
            - { name: form.type, alias: oro_sorting_choice }

    oro_query_designer.form.type.query_designer_column:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\ColumnType
        tags:
            - { name: form.type, alias: oro_query_designer_column }

    oro_query_designer.form.type.query_designer_filter:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\FilterType
        tags:
            - { name: form.type, alias: oro_query_designer_filter }

    oro_query_designer.form.type.query_designer_grouping:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\GroupingType
        arguments:
            - '@oro_query_designer.query_designer.manager'
        tags:
            - { name: form.type, alias: oro_query_designer_grouping }

    oro_query_designer.form.type.query_designer_date_grouping:
        class: Oro\Bundle\QueryDesignerBundle\Form\Type\DateGroupingType
        tags:
            - { name: form.type, alias: oro_query_designer_date_grouping }
