services:
    oro_entity.form.type.custom_entity:
        class: Oro\Bundle\EntityBundle\Form\Type\CustomEntityType
        tags:
            - { name: form.type, alias: custom_entity_type }

    oro_entity.form.type.entity_choice:
        class: Oro\Bundle\EntityBundle\Form\Type\EntityChoiceType
        arguments:
            - '@oro_entity.entity_provider'
        tags:
            - { name: form.type, alias: oro_entity_choice }

    oro_entity.form.type.entity_field_choice:
        class: Oro\Bundle\EntityBundle\Form\Type\EntityFieldChoiceType
        arguments:
            - '@oro_entity.entity_provider'
            - '@oro_entity.entity_field_provider'
            - '@translator'
        tags:
            - { name: form.type, alias: oro_entity_field_choice }

    oro_entity.form.type.entity_field_select:
        class: Oro\Bundle\EntityBundle\Form\Type\EntityFieldSelectType
        arguments:
            - '@oro_entity.entity_provider'
            - '@oro_entity.entity_field_provider'
            - '@translator'
        tags:
            - { name: form.type, alias: oro_entity_field_select }

    oro_entity.form.type.entity_select:
        class: Oro\Bundle\EntityBundle\Form\Type\EntitySelectType
        arguments:
            - '@oro_entity_config.config_manager'
        tags:
            - { name: form.type, alias: oro_entity_select }

    oro_entity.form.handler.entity_select:
        class: Oro\Bundle\EntityBundle\Form\Handler\EntitySelectHandler
        calls:
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
            - [setAclHelper, ["@oro_security.acl_helper"]]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: entity_select, acl_resource: oro_search }

    oro_entity.form.guesser.form_config:
        class: Oro\Bundle\EntityBundle\Form\Guesser\FormConfigGuesser
        arguments:
            - '@doctrine'
            - '@oro_entity_config.provider.entity'
            - '@oro_entity_config.provider.form'
        tags:
            - { name: form.type_guesser, priority: 20 }

    oro_entity.form.guesser.doctrine_type:
        class: Oro\Bundle\EntityBundle\Form\Guesser\DoctrineTypeGuesser
        arguments:
            - '@doctrine'
            - '@oro_entity_config.provider.entity'
        calls:
            # default types
            - [addDoctrineTypeMapping, ["string", Symfony\Component\Form\Extension\Core\Type\TextType]]
            - [addDoctrineTypeMapping, ["integer", Symfony\Component\Form\Extension\Core\Type\TextType]] # to be able validate numbers properly, we need text input
            - [addDoctrineTypeMapping, ["smallint", Symfony\Component\Form\Extension\Core\Type\IntegerType, { precision: 0 }]]
            - [addDoctrineTypeMapping, ["bigint", Symfony\Component\Form\Extension\Core\Type\IntegerType, { precision: 0 }]]
            - [addDoctrineTypeMapping, ["boolean", Symfony\Component\Form\Extension\Core\Type\CheckboxType]]
            - [addDoctrineTypeMapping, ["decimal", Symfony\Component\Form\Extension\Core\Type\NumberType]]
            - [addDoctrineTypeMapping, ["date", Oro\Bundle\FormBundle\Form\Type\OroDateType]]
            - [addDoctrineTypeMapping, ["time", Symfony\Component\Form\Extension\Core\Type\TimeType, { model_timezone: "UTC", view_timezone: "UTC" }]]
            - [addDoctrineTypeMapping, ["datetime", Oro\Bundle\FormBundle\Form\Type\OroDateTimeType]]
            - [addDoctrineTypeMapping, ["datetimetz", Oro\Bundle\FormBundle\Form\Type\OroDateTimeType]]
            - [addDoctrineTypeMapping, ["text", Symfony\Component\Form\Extension\Core\Type\TextareaType]]
            - [addDoctrineTypeMapping, ["float", Symfony\Component\Form\Extension\Core\Type\NumberType]]
            - [addDoctrineTypeMapping, ["guid", Symfony\Component\Form\Extension\Core\Type\TextType]]
            # custom types
            - [addDoctrineTypeMapping, ["percent", Oro\Bundle\FormBundle\Form\Type\OroPercentType]]
            - [addDoctrineTypeMapping, ["money", Oro\Bundle\FormBundle\Form\Type\OroMoneyType]]
            # cannot set default form types for compound and binary types (array, object, blob)
        tags:
            - { name: form.type_guesser, priority: 10 }


    oro_entity.form.type.entity_field_fallback_value:
        class: 'Oro\Bundle\EntityBundle\Form\Type\EntityFieldFallbackValueType'
        arguments:
            - "@oro_entity.fallback.resolver.entity_fallback_resolver"
        tags:
            - { name: form.type, alias: oro_entity_fallback_value }
