services:
    oro_layout.php.renderer:
        public: false
        class: Oro\Component\Layout\Renderer
        arguments:
            - '@oro_layout.php.renderer.engine'

    oro_layout.php.renderer.engine:
        public: false
        class: Oro\Bundle\LayoutBundle\Form\RendererEngine\TemplatingRendererEngine
        arguments:
            - '@templating.engine.php'
            - '%oro_layout.php.resources%'

    oro_layout.php.layout_renderer:
        public: false
        class: Oro\Component\Layout\LayoutRenderer
        arguments:
            - '@oro_layout.php.renderer'
            - '@templating.form.engine'

    oro_layout.php.templating.helper:
        class: Oro\Component\Layout\Templating\Helper\LayoutHelper
        arguments:
            - '@oro_layout.php.renderer'
            - '@oro_layout.text.helper'
            - '@templating.form.engine'
        tags:
             - { name: templating.helper, alias: layout }

    oro_layout.templating.form.engine:
        class: Oro\Bundle\LayoutBundle\Form\RendererEngine\TemplatingRendererEngine
        decorates: 'templating.form.engine'
        parent: 'templating.form.engine'
