services:
    oro_layout.view.listener:
        class: Oro\Bundle\LayoutBundle\EventListener\LayoutListener
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            # process the '@Layout' annotation before the '@Template' annotation
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 10 }
            - { name: container.service_subscriber }
