services:
    oro_digital_asset.provider.file_constraints:
        parent: oro_attachment.provider.file_constraints
        # Public because used in digital-asset-grid
        public: true

    oro_digital_asset.provider.preview_metadata:
        class: Oro\Bundle\DigitalAssetBundle\Provider\PreviewMetadataProvider
        # Public because used in digital-asset-select-file-grid
        public: true
        arguments:
            - '@oro_attachment.provider.file_url'
            - '@oro_attachment.tools.mime_type_checker'
            - '@oro_attachment.provider.file_icon'
            - '@oro_attachment.provider.file_title'

    oro_digital_asset.form.type.digital_asset:
        class: Oro\Bundle\DigitalAssetBundle\Form\Type\DigitalAssetType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    oro_digital_asset.form.type.digital_asset_in_dialog:
        class: Oro\Bundle\DigitalAssetBundle\Form\Type\DigitalAssetInDialogType
        tags:
            - { name: form.type }

    oro_digital_asset.acl.voter.digital_asset_deletion:
        class: Oro\Bundle\DigitalAssetBundle\Acl\Voter\DigitalAssetDeleteVoter
        tags:
            - { name: security.voter }

    oro_digital_asset.listener.source_changed_listener:
        class: Oro\Bundle\DigitalAssetBundle\EventListener\DigitalAssetSourceChangedListener
        arguments:
            - '@oro_digital_asset.reflector.file_reflector'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\AttachmentBundle\Entity\File', event: postUpdate }

    oro_digital_asset.reflector.file_reflector:
        class: Oro\Bundle\DigitalAssetBundle\Reflector\FileReflector
        arguments:
            - '@property_accessor'
        calls:
            - [setLogger, ['@logger']]

    oro_digital_asset.listener.file_digital_asset_changed:
        class: Oro\Bundle\DigitalAssetBundle\EventListener\FileDigitalAssetChangedListener
        arguments:
            - '@oro_digital_asset.reflector.file_reflector'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\AttachmentBundle\Entity\File', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\AttachmentBundle\Entity\File', event: preUpdate }

    oro_digital_asset.form.transformer.digital_asset_to_id:
        class: Oro\Bundle\FormBundle\Form\DataTransformer\EntityToIdTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - Oro\Bundle\DigitalAssetBundle\Entity\DigitalAsset
            - id

    oro_digital_asset.form.extension.digital_asset_manager:
        class: Oro\Bundle\DigitalAssetBundle\Form\Extension\DigitalAssetManagerExtension
        arguments:
            - '@oro_attachment.provider.attachment_entity_config'
            - '@oro_entity.entity_class_name_helper'
            - '@oro_digital_asset.provider.preview_metadata'
            - '@oro_digital_asset.form.transformer.digital_asset_to_id'
            - '@oro_digital_asset.reflector.file_reflector'
        tags:
            - { name: form.type_extension }

    oro_digital_asset.provider.file_title:
        decorates: oro_attachment.provider.file_title
        class: Oro\Bundle\DigitalAssetBundle\Provider\FileTitleProvider
        arguments:
            - '@oro_digital_asset.provider.file_title.inner'
            - '@oro_locale.helper.localization'
            - '@doctrine'

    oro_digital_asset.listener.file_delete_listener:
        decorates: oro_attachment.listener.file_delete_listener
        class: Oro\Bundle\DigitalAssetBundle\EventListener\FileDeleteListener
        arguments:
            - '@oro_digital_asset.listener.file_delete_listener.inner'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\AttachmentBundle\Entity\File', event: preRemove }
