services:
    Oro\Bundle\DigitalAssetBundle\Validator\Constraints\DigitalAssetSourceFileMimeTypeValidator:
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_attachment.tools.mime_type_checker'
            - '@router'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: validator.constraint_validator }
