services:
    _defaults:
        public: true

    Oro\Bundle\EmailBundle\Controller\AutoResponseRuleController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_email.autoresponserule_manager }

    Oro\Bundle\EmailBundle\Controller\Dashboard\DashboardController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
