services:
    oro_entity_config.metadata.annotation_metadata_factory:
        class: Metadata\MetadataFactory
        arguments:
            - '@oro_entity_config.metadata.annotation_driver'

    oro_entity_config.metadata.annotation_driver:
        class: Oro\Bundle\EntityConfigBundle\Metadata\Driver\AnnotationDriver
        arguments:
            - '@annotation_reader'
