services:
    _defaults:
        public: true

    Oro\Bundle\ReportBundle\Controller\ReportController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_report.entity_provider }
