services:
    oro_report.form.type.report:
        class: Oro\Bundle\ReportBundle\Form\Type\ReportType
        tags:
            - { name: form.type, alias: oro_report }

    oro_report.form.handler.report:
        class: Oro\Bundle\ReportBundle\Form\Handler\ReportHandler
        arguments:
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    Oro\Bundle\ReportBundle\Form\Handler\ReportHandler:
        alias: oro_report.form.handler.report

    oro_report.report.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        public: true
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\ReportBundle\Entity\Report'
            - '@doctrine.orm.entity_manager'

    oro_report.form.type.entity_choice:
        class: Oro\Bundle\ReportBundle\Form\Type\ReportEntityChoiceType
        arguments:
            - '@oro_report.entity_provider'
        tags:
            - { name: form.type, alias: oro_report_entity_choice }

    oro_report.form.type.chart:
        class: Oro\Bundle\ReportBundle\Form\Type\ReportChartType
        tags:
            - { name: form.type, alias: oro_report_chart }

    oro_report.form.type.chart.schema:
        class: Oro\Bundle\ReportBundle\Form\Type\ReportChartSchemaType
        arguments:
            - '@oro_query_designer.query_designer.manager'
        tags:
            - { name: form.type, alias: oro_report_chart_data_schema }

    oro_report.form.type.chart.schema.collection:
        class: Oro\Bundle\ReportBundle\Form\Type\ReportChartSchemaCollectionType
        arguments:
            - '@oro_chart.config_provider'
        tags:
            - { name: form.type, alias: oro_report_chart_data_schema_collection }
