services:
    oro_segment.form.type.segment:
        class: Oro\Bundle\SegmentBundle\Form\Type\SegmentType
        tags:
            - { name: form.type, alias: oro_segment }

    oro_segment.form.type.segment_filter_builder:
        class: Oro\Bundle\SegmentBundle\Form\Type\SegmentFilterBuilderType
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@security.token_storage'
        tags:
            - { name: form.type, alias: oro_segment_filter_builder }

    oro_segment.form.type.segment_choice:
        class: 'Oro\Bundle\SegmentBundle\Form\Type\SegmentChoiceType'
        arguments:
            - '@doctrine'
            - '@oro_security.acl_helper'
        tags:
            - { name: form.type}

    oro_segment.form.segment:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "oro_segment_form"
            - Oro\Bundle\SegmentBundle\Form\Type\SegmentType

    oro_segment.form.handler.segment:
        class: Oro\Bundle\SegmentBundle\Form\Handler\SegmentHandler
        arguments:
            - '@request_stack'
            - '@doctrine'
            - '@oro_segment.static_segment_manager'

    Oro\Bundle\SegmentBundle\Form\Handler\SegmentHandler:
        alias: oro_segment.form.handler.segment

    oro_segment.form.type.entity_choice:
        class: Oro\Bundle\SegmentBundle\Form\Type\SegmentEntityChoiceType
        arguments:
            - '@oro_segment.entity_provider'
        tags:
            - { name: form.type, alias: oro_segment_entity_choice }
