services:
    oro_message_queue.test.message_collector:
        class: Oro\Bundle\MessageQueueBundle\Test\Functional\MessageCollector
        decorates: oro_message_queue.client.message_producer
        arguments:
            - '@oro_message_queue.test.message_collector.inner'

    oro_message_queue.async.basic_message_processor:
        class: Oro\Component\MessageQueue\Test\Async\BasicMessageProcessor
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_message_queue.async.unique_message_processor:
        class: Oro\Component\MessageQueue\Test\Async\UniqueMessageProcessor
        arguments:
            - '@oro_message_queue.job.runner'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_message_queue.async.dependent_message_processor:
        class: Oro\Component\MessageQueue\Test\Async\DependentMessageProcessor
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.job.dependent_job_service'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_message_queue.async.change_config:
        class: Oro\Bundle\MessageQueueBundle\Test\Async\ChangeConfigProcessor
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
