placeholders:
    placeholders:
        update_navButtons_after:
            items:
                oro_save_as_draft: ~
                oro_save_as_new_draft: ~

    items:
        oro_save_as_draft:
            template: OroDraftBundle:Draft:saveAsDraft.html.twig
            applicable:
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\DraftBundle\Entity\DraftableInterface)'
                - '@oro_ui.placeholder.filter->isTrue($entity.id$)'
                - '@oro_ui.placeholder.filter->isSame($entity.draftUuid$, $null$)'
                - '@oro_draft.placeholder.filter->isApplicable($entity$)'

        oro_save_as_new_draft:
            template: OroDraftBundle:Draft:saveAsNewDraft.html.twig
            applicable:
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\DraftBundle\Entity\DraftableInterface)'
                - '@oro_ui.placeholder.filter->isTrue($entity.id$)'
                - '@oro_ui.placeholder.filter->isTrue($entity.draftUuid$)'
                - '@oro_draft.placeholder.filter->isApplicable($entity$)'
