services:
    oro_currency.form.type.currency_selection:
        class: Oro\Bundle\CurrencyBundle\Form\Type\CurrencySelectionType
        arguments:
            - '@oro_currency.config.currency'
            - '@oro_locale.settings'
            - '@oro_currency.helper.currency_name'
        tags:
            - { name: form.type, alias: oro_currency_selection }

    oro_currency.form.type.price:
        class: Oro\Bundle\CurrencyBundle\Form\Type\PriceType
        calls:
            - [setDataClass, ['%oro_currency.price.model%']]
        tags:
            - { name: form.type, alias: oro_currency_price }

    oro_currency.form.type.multicurrency:
        class: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
        calls:
            - [setDataClass, [Oro\Bundle\CurrencyBundle\Entity\MultiCurrency]]
        tags:
            - { name: form.type, alias: oro_multicurrency }

    oro_currency.form.type.currency:
        class: Oro\Bundle\CurrencyBundle\Form\Type\CurrencyType
        tags:
            - { name: form.type, alias: oro_currency }
