aliases:
    oro/datagrid/cell/multi-currency-cell$: orocurrency/js/datagrid/cell/multi-currency-cell
dynamic-imports:
    orocurrency:
        - orocurrency/js/app/views/editor/multi-currency-editor-view
        - orocurrency/js/app/views/multicurrency-control-view
        - orocurrency/js/datagrid/inline-editing/currency-save-api-accessor
    orodatagrid:
        - oro/datagrid/cell/multi-currency-cell
