services:
    oro_entity_pagination.datagrid.extension.orm_entity_pagination:
        class: Oro\Bundle\EntityPaginationBundle\Datagrid\EntityPaginationExtension
        tags:
            - { name: oro_datagrid.extension }

    oro_entity_pagination.storage:
        class: Oro\Bundle\EntityPaginationBundle\Storage\EntityPaginationStorage
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity_pagination.manager'
            - '@request_stack'

    oro_entity_pagination.storage.data_collector:
        class: Oro\Bundle\EntityPaginationBundle\Storage\StorageDataCollector
        arguments:
            - '@oro_datagrid.datagrid.manager.link'
            - '@oro_entity.doctrine_helper'
            - '@oro_entity_pagination.storage'
            - '@oro_entity_pagination.manager'

    oro_entity_pagination.manager:
        class: Oro\Bundle\EntityPaginationBundle\Manager\EntityPaginationManager
        arguments:
            - '@oro_config.user'

    oro_entity_pagination.message_manager:
        class: Oro\Bundle\EntityPaginationBundle\Manager\MessageManager
        public: true
        arguments:
            - '@session'
            - '@translator'
            - '@oro_entity_pagination.navigation'
            - '@oro_entity_pagination.storage'

    oro_entity_pagination.navigation:
        class: Oro\Bundle\EntityPaginationBundle\Navigation\EntityPaginationNavigation
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@security.authorization_checker'
            - '@oro_entity_pagination.storage'

    oro_entity_pagination.event_listener.entity_pagination:
        class: Oro\Bundle\EntityPaginationBundle\EventListener\EntityPaginationListener
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity_pagination.storage'
            - '@oro_entity_pagination.manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after, method: onResultAfter }

    oro_entity_pagination.twig_extension.entity_pagination:
        class: Oro\Bundle\EntityPaginationBundle\Twig\EntityPaginationExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }
