entity_config:
    dataaudit:
        entity:
            items:
                auditable:
                    options:
                        priority:           60
                        default_value:      false
                        indexed:            true
                    grid:
                        type:               boolean
                        label:              oro.dataaudit.entity_config.entity.items.auditable
                        filter_type:        boolean
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        false
                    form:
                        type:               Oro\Bundle\EntityConfigBundle\Form\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.dataaudit.entity_config.entity.items.auditable

                    # this attribute can be used to prohibit changing the auditable state (no matter whether
                    # it is enabled or not) for the entity
                    # if TRUE than the current state cannot be changed
                    immutable: # boolean
                        options:
                            auditable: false
        field:
            items:
                auditable:
                    options:
                        value_type:         boolean
                        priority:           60
                        default_value:      false
                        allowed_type:       [string, text, integer, smallint, bigint, boolean, datetime, date, time, float, decimal, money, percent, enum, multiEnum, oneToMany, oneToOne, manyToOne, manyToMany, array, simple_array, json_array, ref-many, ref-one]
                    grid:
                        type:               boolean
                        label:              oro.dataaudit.entity_config.field.items.auditable
                        required:           true
                        sortable:           true
                    form:
                        type:               Oro\Bundle\EntityConfigBundle\Form\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.dataaudit.entity_config.field.items.auditable

                    # this attribute can be used to prohibit changing the auditable state (no matter whether
                    # it is enabled or not) for the entity field
                    # if TRUE than the current state cannot be changed
                    immutable: # boolean
                        options:
                            auditable: false

                propagate:
                    options:
                        value_type:         boolean
                        priority:           70
                        default_value:      false
                        allowed_type:       [oneToMany, oneToOne, manyToOne, manyToMany, ref-many, ref-one]
                        required_property:
                            config_id:
                                scope:      dataaudit
                            code:           auditable
                            value:          true
                    form:
                        type:               Oro\Bundle\EntityConfigBundle\Form\Type\ChoiceType
                        options:
                            choices:
                                No:         0
                                Yes:        1
                            placeholder:    false
                            block:          other
                            label:          oro.dataaudit.entity_config.field.items.propagate
                            tooltip:        oro.dataaudit.entity_config.field.items.propagate.tooltip

                    # this attribute can be used to prohibit changing the auditable state (no matter whether
                    # it is enabled or not) for the entity field
                    # if TRUE than the current state cannot be changed
                    immutable: # boolean
                        options:
                            auditable: false
